<%@include file="../../includes/startInc.jsp" %><html lang="<%=biz.statum.apia.web.bean.BasicBeanStatic.getUserDataStatic(request).getLangCode()%>"><head><%@include file="../../includes/headInclude.jsp" %><script type="text/javascript" src="<system:util show="context" />/page/query/entity/list.js"></script><script type="text/javascript" src="<system:util show="context" />/page/query/common/queryButtons.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminFav.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminActions.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/campaigns.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/navButtons.js"></script><script type="text/javascript">
		var URL_REQUEST_AJAX = '/apia.query.EntityInstanceAction.run';
		var ADDITIONAL_INFO_IN_TABLE_DATA  = false;
		
		var FLAG_BTN_CREATE = toBoolean('<system:query show="flagValue" from="theQuery" field="2" defaultValue="qryButtons" />');
		var FLAG_BTN_UPDATE = toBoolean('<system:query show="flagValue" from="theQuery" field="3" defaultValue="qryButtons" />');
		var FLAG_BTN_DELETE = toBoolean('<system:query show="flagValue" from="theQuery" field="4" defaultValue="qryButtons" />');
		var FLAG_BTN_DEPENDENCIES = toBoolean('<system:query show="flagValue" from="theQuery" field="5" defaultValue="qryButtons" />');
		var FLAG_BTN_CLONE = toBoolean('<system:query show="flagValue" from="theQuery" field="21" defaultValue="qryButtons" />');
		
		var LBL_CANT_CREATE_INST = '<system:label show="text" label="msgCantCreateInst" forScript="true" />';
		var LBL_CANT_UPDATE_INST = '<system:label show="text" label="msgCantModInst" forScript="true" />';
		var LBL_CANT_DELETE_INST = '<system:label show="text" label="msgCantDelInst" forScript="true" />';
	</script></head><body><div class="body" id="bodyDiv"><form id="queryForm" action="<system:util show="context" />/apia.query.EntityInstanceAction.run?<system:util show="tabIdRequest" />" method="post"><input type="hidden" name="action" value="" id="queryFormAction"><div class="optionsContainer" id="optionsContainer" style="position: absolute;"><system:campaign inLogin="false" inSplash="false" location="verticalUp" /><%@include file="../common/panelInfo.jsp" %><div class="fncPanel options"><div class="title"><system:label show="text" label="titActions"/></div><div class="content"><div id="btnSearch" class="button suggestedAction"><system:label show="text" label="btnSearch" /></div><system:query show="ifFlag" from="theQuery" field="0" defaultValue="qryButtons"><div id="btnExport" class="button"><system:label show="text" label="btnExport" /></div></system:query></div></div><system:query show="ifNotFlag" from="theQuery" field="21"><system:query show="ifValue" from="theBean" field="hasFiltersWithType" value="true"><div class="fncPanel options"><div class="title"><system:label show="text" label="titOptions"/></div><div class="content"><div id="btnFilterType" class="button large"><system:label show="text" label="btnFilterType" /></div></div></div></system:query></system:query><%@include file="../../includes/adminActions.jsp" %><%@include file="../common/additionalFilters.jsp" %><system:campaign inLogin="false" inSplash="false" location="verticalDown" /></div><div class="gridContainer" id="gridContainer"><system:campaign inLogin="false" inSplash="false" location="horizontalUp" /><%@include file="../common/columnsHeader.jsp" %><%@include file="../common/columnsValue.jsp" %><%@include file="../common/navButtons.jsp" %><system:campaign inLogin="false" inSplash="false" location="horizontalDown" /></div></form></div><%@include file="../../includes/footer.jsp" %></body></html>
