<%@include file="../../includes/startInc.jsp" %><html><head><%@include file="../../includes/headInclude.jsp" %><script type="text/javascript" src="<system:util show="context" />/page/design/businessclasses/testRestService.js"></script></head><script type="text/javascript">
	var URL_REQUEST_AJAX = '/apia.design.BusinessClassesAction.run';
	var LBL_JSON_PATH = '<system:label show="text" label="lblJsonPath" forScript="true" />';
	var LBL_XPATH = '<system:label show="text" label="lblXPath" forScript="true" />';
	
	var MSG_REST_HELP_1 = '<system:label show="text" label="msgRestHelp1" forScript="true" />';
	var MSG_REST_HELP_2 = '<system:label show="text" label="msgRestHelp2" forScript="true" />';
	var MSG_REST_HELP_3 = '<system:label show="text" label="msgRestHelp3" forScript="true" />';
	var MSG_REST_HELP_4 = '<system:label show="text" label="msgRestHelp4" forScript="true" />';
	var MSG_REST_HELP_5 = '<system:label show="text" label="msgRestHelp5" forScript="true" />';
	var MSG_REST_HELP_6 = '<system:label show="text" label="msgRestHelp6" forScript="true" />';
	var MSG_REST_HELP_7 = '<system:label show="text" label="msgRestHelp7" forScript="true" />';
	
</script><body><div class="body" id="bodyDiv" style="padding: 0 10px 0 10px; overflow: hidden; "><form id="frmTestRestWS" action="post" style="height: inherit;"><div style="width:50%;height:100%;float:left"><!-- Informarción básica de la CN Rest --><input name="txtUri" type="hidden"><input name="cmbRestTypeTag" type="hidden"><input name="cmbRestHttpMetTag" type="hidden"><input name="cmbType" type="hidden"><div class="fieldGroup" style="padding-right:20px;height: inherit;"><div style="height:50%;"><div class="title"><system:label show="text" label="titPar" /></div><div id="parameters"><div id="paramGridHeader" class="gridHeader"><table><thead><tr class="header"><th width="35%"><system:label show="text" label="lblNom" /></th><th width="65%"><system:label show="text" label="lblValue" /></th></tr></thead></table></div><div class="gridBody" style="height:160px; border-bottom: 1px solid #DDDDDD;"><table style="table-layout: fixed;"><tbody class="tableData" id="gridBodyParams"></tbody></table></div></div></div><div style="height: 50%;"><div class="title"><system:label show="text" label="lblHelp" /></div><div id="helpContainer"><div class="gridHeader"><table><thead><tr class="header" id="helpTableHeader"><th width="35%"></th><th width="65%"><system:label show="text" label="sbtRes" /></th></tr></thead></table></div><div class="gridBody" style="height:160px;"><table style="table-layout: fixed;"><tbody class="tableData" id="gridBodyHelp"></tbody></table></div></div></div></div></div><div style="width:49%;float:left"><div class="fieldGroup"><div class="title"><system:label show="text" label="lblSrvRes" /></div><div id="filter" style="padding-bottom:10px"><div class="field fieldOneFifths" style="float:left;"><label><system:label show="text" label="lblEjeFilter" />:</label><select name="cmbFilter" onchange="showPath(this)"><option value="N"><system:label show="text" label="lblNo" /></option><option value="Y"><system:label show="text" label="lblYes" /></option></select></div><div id="labelPath" class="field fieldTwoFifths" style="float:left;"><label></label><input id="filterPath" name="filterPath" disabled class="validate['required']"></input></div><div class="field fieldTwoFifths"><div id="btnTest" class="modalBottomBarConfirm suggestedAction"><button type="button" class="genericBtn suggestedAction"><span><system:label show="text" label="lblInvSrv" /></span></button></div></div></div><textarea id="restResponse" cols="1" style="width:99%; height:345px"></textarea></div></div></form></div></body>

