<%@page import="com.dogma.Configuration"%><%@page import="biz.statum.sdk.util.HttpServletRequestResponse"%><%@page import="biz.statum.apia.web.bean.BasicBeanStatic"%><%@page import="biz.statum.sdk.util.StringUtil"%><%@ taglib uri='/WEB-INF/regions.tld' prefix='region' %><%@ taglib prefix="system"	uri="/WEB-INF/system-tags.tld" %><%
String template = "/page/templates/entityDefault.jsp";
if (StringUtil.notEmpty(request.getParameter("template"))){
	template = request.getParameter("template");
}
out.clear();
%><region:render template='<%=template%>'><region:put section='title'><div class="titImage"><img title="<system:label show="text" label="lblEjeTitPriPro2"/>" src="<system:util show="context" />/css/<system:util show="currentStyle" />/img/priority2.gif" alt=""></div><div class='proTitle'><system:label show="text" label="lblTempTit" /></div></region:put><region:put section="tskDescription"><system:label show="text" label="lblTempDesc" /></region:put><region:put section="taskImage"><img src="<system:util show="context" />/css/<system:util show="currentStyle" />/img/functionalities/Tareas.gif"></region:put><region:put section='entityMain'><div class="fieldGroup"><div class="title"><system:label show="tooltip" label="sbtEjeDatEnt" /></div><div class="field required"><label title="<system:label show="tooltip" label="lblEjeIdeEnt" />"><system:label show="text" label="lblEjeIdeEnt" />:</label><b><system:label show="text" label="lblAutNum"/></b></div><div class="field"><label title="<system:label show="tooltip" label="lblEjeTipEnt" />"><system:label show="text" label="lblEjeTipEnt" /><system:label show="separator" label=""/></label><b><system:label show="text" label="lblExample"/></b></div></div><div class="fieldGroup"><div class="field"><label title="<system:label show="tooltip" label="lblEjeUsuCreEnt" />"><system:label show="text" label="lblEjeUsuCreEnt" /><system:label show="separator" label=""/></label></div><div class="field"><label title="<system:label show="tooltip" label="lblEjeFecCreEnt" />"><system:label show="text" label="lblEjeFecCreEnt" /><system:label show="separator" label=""/></label></div></div></region:put><region:put section='entityDocuments'><div class="fieldGroup"><div class="title"><system:label show="text" label="sbtEjeDocEnt" /></div><div class="fieldGroup" id="docContentE"><div class="divAdder"><div class="modalOptionsContainer" id="prmDocumentContainterE"><div class="element docAddDocument" id="docAddDocumentE" helper="true"><div class="option optionAdd"><system:label show="text" label="btnAgr" /></div></div></div></div><div class="clear"></div></div></div></region:put><region:put section='entityForms'><div class="fieldGroup"><div class="title"><system:label show="text" label="tabEjeFor" /></div><div class="field"><label title="<system:label show="tooltip" label="lblField" />&nbsp;1"><system:label show="text" label="lblField" />&nbsp;1:&nbsp;</label><select class="readonly" value=""></select></div><div class="field"><label title="<system:label show="tooltip" label="lblField" />&nbsp;2"><system:label show="text" label="lblField" />&nbsp;2:&nbsp;</label><input type="text" class="readonly" value=""></div></div></region:put><region:put section='scripts_include'><link href="<system:util show="context" />/css/<system:util show="currentStyle" />/monitor.css" rel="stylesheet" type="text/css"><script type="text/javascript">
			function initPage(){}
		</script><link href="<system:util show="context" />/css/<system:util show="currentStyle" />/tskSchedulerExec.css" rel="stylesheet" type="text/css" ></region:put><region:put section='buttons'><div id="divAdminActEdit" class="fncPanel buttons"><div class="title"><system:label show='text' label='titActions'/></div><div class="content"><div id="btnConf" class="button submit suggestedAction" title="<system:label show="tooltip" label="btnCon" />"><system:label show="text" label="btnCon" /></div><div id="btnSave" class="button" title="<system:label show="tooltip" label="btnGua"/>"><system:label show="tooltip" label="btnGua"/></div></div></div></region:put><region:put section="helpDocuments"><div class="title"><system:label show="text" label="mnuOpc"/></div><div class="content"><div id="btnViewDocs" class="button" title="<system:label show="tooltip" label="sbtEjeDoc" />"><system:label show="text" label="sbtEjeDoc" /></div><div id="btnPrintFrm" class="button" title="<system:label show="tooltip" label="btnStaPri" />"><system:label show="text" label="btnStaPri" /></div></div></region:put></region:render>
	
