<%@page import="com.dogma.vo.OrgUnitAdminsVo"%><%@page import="com.dogma.vo.OrganizationalUnitVo"%><%@page import="biz.statum.sdk.util.HttpServletRequestResponse"%><%@page import="biz.statum.apia.web.action.administration.OrganizationalUnitAction"%><%@page import="biz.statum.apia.web.bean.administration.OrganizationalUnitBean"%><%@include file="../../includes/startInc.jsp" %><html><head><%@include file="../../includes/headInclude.jsp" %><link href="<system:util show="context" />/css/<system:util show="currentStyle" />/generalAdm.css" rel="stylesheet" type="text/css" ><script type="text/javascript" src="<system:util show="context" />/page/administration/orgUnit/edit.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminActionsEdition.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminFav.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/navButtons.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/campaigns.js"></script><script type="text/javascript" src="<system:util show="context" />/page/modals/pools.js"></script><script type="text/javascript" src="<system:util show="context" />/page/modals/users.js"></script><script type="text/javascript">
		var URL_REQUEST_AJAX = '/apia.administration.OrganizationalUnitAction.run';
		var currentEnvId = "<system:edit show="value" from="theBean" field="currentEnvironmentId"/>";
		var ADDITIONAL_INFO_IN_TABLE_DATA = false;
		var POOL_ID = "<system:edit show="value" from="theEdition" field="poolId"/>";
		var POOL_NAME = "<system:edit show="value" from="theEdition" field="poolName"/>";
		var ADMINS = [<%
			OrganizationalUnitBean dBean = (OrganizationalUnitBean)OrganizationalUnitAction.staticRetrieveBean(new HttpServletRequestResponse(request, response));
			OrganizationalUnitVo vo = dBean.getEditionObject();
			Collection<OrgUnitAdminsVo> admins = vo.getOrgUnitAdmins();
			if(admins != null) {
				int i = 0;
				for(OrgUnitAdminsVo admin : admins) {
					out.write("\"" + admin.getUsrLogin() + "\"");
					if(i < admins.size() - 1)
						out.write(", ");
					i++;
				}
			}
		%>];
	</script></head><body><div id="exec-blocker"></div><div class="header"></div><div class="body" id="bodyDiv"><form id="frmData"><div class="optionsContainer"><system:campaign inLogin="false" inSplash="false" location="verticalUp" /><div class="fncPanel info"><div class="title"><system:label show="tooltip" label="mnuOrgUnit" /><%@include file="../../includes/adminFav.jsp" %></div><div class="content divFncDescription"><div class="fncDescriptionImage" src="<system:edit show="value" from="theBean" field="fncImage"/>"></div><div id="fncDescriptionText"><system:label show="text" label="dscFncOrgUnit"/></div><div class="clear"></div></div></div><%@include file="../../includes/adminActionsEdition.jsp" %><system:campaign inLogin="false" inSplash="false" location="verticalDown" /></div><div class="dataContainer"><div class='tabComponent' id="tabComponent"><div class="aTabHeader"><system:campaign inLogin="false" inSplash="false" location="horizontalUp" /></div><div class="aTab"><div class="tab"><system:label show="text" label="tabDatGen" /></div><div class="contentTab"><div class="fieldGroup"><div class="title"><system:label show="tooltip" label="sbtDat" /></div><div class="field fieldTwoFifths required"><label title="<system:label show="tooltip" label="lblNom" />"><system:label show="text" label="lblNom" />:</label><input type="text" name="orgUnitName" id="orgUnitName" class="validate['required','~validName']"  value="<system:edit show="value" from="theEdition" field="orgUnitName"/>" maxlength="255"></div></div><div class="fieldGroup"><div class="field"><label title="<system:label show="tooltip" label="lblProPool" />"><system:label show="text" label="lblProPool" />:</label><div class="modalOptionsContainer" id="poolsContainter"><div class="element" id="addPool" helper="true"><div class="option optionAdd"><system:label show="text" label="btnAgr" /></div></div></div></div></div><div class="fieldGroup"><div class="field fieldFull"><label title="<system:label show="tooltip" label="lblOrgUnitUsrAdmin" />"><system:label show="text" label="lblOrgUnitUsrAdmin" />:</label><div class="modalOptionsContainer" id="usersContainter"><div class="element" id="addUser" helper="true"><div class="option optionAdd"><system:label show="text" label="btnAgr" /></div></div></div></div></div></div></div></div><system:campaign inLogin="false" inSplash="false" location="horizontalDown" /></div></form></div><!-- MODALS --><%@include file="../../modals/pools.jsp" %><%@include file="../../modals/users.jsp" %><%@include file="../../includes/footer.jsp" %></body></html>

