function initPermissionsTab(mode) {

	//Configuramos acci�n del bot�n de agregar permisos
	if ($('prmAddPool')) { 
		$('prmAddPool').addEvent("click", function(e) {
			e.stop();
			//setear variables de configuracion del modal de grupos
			POOLMODAL_SHOWAUTOGENERATED = true;
			POOLMODAL_SHOWNOTAUTOGENERATED = true;
			POOLMODAL_SHOWGLOBAL = true;
			POOLMODAL_SHOWCURRENTENV = true;
			ADDITIONAL_INFO_IN_TABLE_DATA = false;
			//abrir modal
			showPoolsModal(prmProcessPoolsModalReturn);
		});
	}
	
	//initPoolMdlPage(); //Para el modal de selecci�n de grupos
	
	loadPermissions(); //Cargamos los grupos con los permisos
	
	
}

//Procesa resultado del modal para seleccionar grupos para asignar permisos
function prmProcessPoolsModalReturn(ret) {
	ret.each(function(e){
		var poolName = e.getRowContent()[0];
		var poolId = e.getRowId();

		addPermissionToContainer(poolName, poolId);
	});
}


//Carga los permisos con acceso de edici�n sobre el widget
function loadPermissions() {
	var request = new Request({
		method: 'post',
		url: CONTEXT + URL_REQUEST_AJAX + '?action=loadWidgetPermissions&isAjax=true' + TAB_ID_REQUEST,
		onRequest: function() { },
		onComplete: function(resText, resXml) { processXMLPerms(resXml); }
	}).send();
}

//Procesa el XML con los permisos de edici�n sobre el cubo
function processXMLPerms(ajaxCallXml){
	if (ajaxCallXml != null) {
		var atts = ajaxCallXml.getElementsByTagName("perms");
		if (atts != null && atts.length > 0 && atts.item(0) != null) {
			atts = atts.item(0).getElementsByTagName("perm");
			for(var i = 0; i < atts.length; i++) {
				var att = atts.item(i);
				
				var pool_id = att.getAttribute("pool_id");
				var pool_name = att.getAttribute("pool_name");
				var perms = att.getAttribute("perms");

				if (pool_id==-1){
					$('selPerAllPoolPerm').selectedIndex = ("RW" == perms) ? 2 : ("R" == perms) ? 1 : 0;
				} else {
					addPermissionToContainer(pool_name, pool_id, perms == "RW");	
				}
			}
		}
	}
}

//Agrega un grupo en el container de permisos 
function addPermissionToContainer(name, id, checked) {
	var content = addActionElement($('divPools'),name, id, "hidPerPoolId");
	if (content == null) return;
	
	new Element('span.checkcontainer', {html: ' ' + LBL_CAN_UPDATE + ': '}).inject(content);
	var checkbox = new Element('input', {type: 'checkbox', name: 'chkPerPoolUpdate' + id, value: 'true'}).inject(content);
	checkbox.addEvent('click', function(evt){ evt.stopPropagation(); });
	if (checked) checkbox.checked = true;
}

//Validaci�n de permisos
function verifyPermissions(){ //Al menos un usuario debe tener permiso de modificacion en el widget
	var someoneCanModify = false;

	getActionElements('divPools').each(function(ele) {
		if(ele.getChildren('input')[1].checked) {
			someoneCanModify = true;
		}
	});
	if($('selPerAllPoolPerm').value == 2){
		someoneCanModify = true;
	}
	if (!someoneCanModify){
		showMessage(MSG_PERMISSIONS_ERROR,null,'modalWarning');	
		return false;
	}
	return true;
}