var addPool;

function initPage(){
	//crear spinner de espere un momento
	sp = new Spinner(document.body,{message:WAIT_A_SECOND});
	
	initAdminFieldOnChangeHighlight();
	initAdminActionsEdition();
	initAdminFav();
	
	getBodyController().canRemoveTab = function() { return ! AT_LEAST_ON_FIELD_INPUT_CHANGED; };
	/*
	addPool = $('addPool');
	
	addPool.addEvent("click", function(e) {
		e.stop();
		//setear variables de configuracion del modal de grupos
		POOLMODAL_SHOWAUTOGENERATED = false;
		POOLMODAL_SHOWNOTAUTOGENERATED = true;
		POOLMODAL_SHOWGLOBAL = true;
		POOLMODAL_SELECTONLYONE = true;
		POOLMODAL_FROMENVS = currentEnvId;
		
		//abrir modal
		showPoolsModal(processPoolsModalReturn);
	});
	
	$('poolsContainter').onRemove = function() {
		addPool.inject($('poolsContainter'));
	};
	
	if(POOL_ID) {
		addActionElement($('poolsContainter'), POOL_NAME, POOL_ID, "poolId");
		addPool.dispose();
	}
	
	
	$('addUser').addEvent("click", function(e) {
		e.stop();
		//setear variables de configuracion del modal de usuarios
		USERMODAL_GLOBAL_AND_ENV = true;
		
		//abrir modal
		showUsersModal(processUsersModalReturn);
	});
	
	if(ADMINS && ADMINS.length) {
		for(var i = 0; i < ADMINS.length; i++) {
			addActionElement($('usersContainter'), ADMINS[i], ADMINS[i], "usrId");
		}
	}
	*/
	
	$('addPool').addEvent("click", function(e) {
		e.stop();
		//setear variables de configuracion del modal de grupos
		POOLMODAL_SHOWAUTOGENERATED = false;
		POOLMODAL_SHOWNOTAUTOGENERATED = true;
		POOLMODAL_SHOWGLOBAL = false;
		POOLMODAL_FROMENVS = currentEnvId;
		POOLMODAL_ONLY_OUTSIDE_HIERARCHY = true;
		
		//abrir modal
		showPoolsModal(processPoolsModalReturn);
	});
	
	if(POOL_IDS && POOL_IDS.length) {
		for(var i = 0; i < POOL_IDS.length; i++) {
			var container = $('poolsContainter');
			container.onRemove = disableConfirm;
			addActionElement(container, POOL_IDS[i][1], POOL_IDS[i][0], "poolId");
		}
	}
	
	$('addPrf').addEvent("click", function(e) {
		e.stop();
		//setear variables de configuracion del modal de perfiles
		PROFILEMODAL_SHOWGLOBAL = false;
		PROFILEMODAL_FROMENVS = currentEnvId;
		
		//abrir modal
		showProfilesModal(processPrfsModalReturn);
	});
	
	if(PRF_IDS && PRF_IDS.length) {
		for(var i = 0; i < PRF_IDS.length; i++) {
			var container = $('prfsContainter');
			container.onRemove = disableConfirm;
			addActionElement(container, PRF_IDS[i][1], PRF_IDS[i][0], "prfId");
		}
	}
	
	var optionGenerateChangeDoc = $('optionGenerateChangeDoc');
	if (optionGenerateChangeDoc) optionGenerateChangeDoc.addEvent('click', function(e) {
		e.stop();
		
		var atts = "";
		var poolsId = document.getElementsByName('poolId');
		for(var i = 0; i < poolsId.length; i++) {
			atts += "&poolId=" + poolsId[i].get('value');
		}
		var prfIds = document.getElementsByName('prfId');
		for(var i = 0; i < prfIds.length; i++) {
			atts += "&prfId=" + prfIds[i].get('value');
		}
		
		//Generar documentaci�n, al terminar habilitar bot�n de confirmar
		new Request({
			url: 'apia.administration.OrganizationalRoleAction.run?action=downloadChangeDoc' + atts + TAB_ID_REQUEST,
			onSuccess: function(responseText, responseXML) {
		    	//AJAX exitoso
		    	if(responseXML && responseXML.childNodes && responseXML.childNodes.length) {
		    		var anchor = new Element('a', {
		    			href: 'page/administration/orgRole/downloadChanges.jsp?path=' + responseXML.childNodes[responseXML.childNodes.length - 1].getAttribute('URL')
		    		});
		    		anchor.inject(document.body);
		    		if(anchor.click) {
		    			anchor.click();
		    		} else if(document.createEvent) {
		    		    var eventObj = document.createEvent('MouseEvents');
		    		    eventObj.initEvent('click', true, true);
		    		    anchor.dispatchEvent(eventObj);
		    		}
		    		enableConfirm();
		    	}
			},
			onFailure: function(responseText, responseXML) {
		    	showMessage(ERR_AT_DOC_ROLE_CHANGE);
			}
		}).send();
		
	});
	
	initPoolMdlPage();
	initPrfMdlPage();
}

function processPoolsModalReturn(ret) {
	if(ret && ret.length)
		disableConfirm();
	
	ret.each(function(e) {
		addActionElement($('poolsContainter'), e.getRowContent()[0], e.getRowId(), "poolId");
	});
}

function processPrfsModalReturn(ret) {
	if(ret && ret.length)
		disableConfirm();
	
	ret.each(function(e) {
		addActionElement($('prfsContainter'), e.getRowContent()[0], e.getRowId(), "prfId");
	});
}

function disableConfirm() {
	if(isCreate)
		return;
	$('btnConf').setStyle('display', 'none');
	var optionGenerateChangeDoc = $('optionGenerateChangeDoc');
	if (optionGenerateChangeDoc) optionGenerateChangeDoc.addClass('suggestedAction').getElement('button').addClass('suggestedAction');
}

function enableConfirm() {
	if(isCreate)
		return;
	$('btnConf').setStyle('display', '');
	var optionGenerateChangeDoc = $('optionGenerateChangeDoc');
	if (optionGenerateChangeDoc) optionGenerateChangeDoc.removeClass('suggestedAction').getElement('button').removeClass('suggestedAction');
}