changeTemplate();


function btnConf_click(){
	if (verifyRequiredObjects()) {
		if(isValidName(document.getElementById("txtName").value)){
			if (verifyPermissions()){
				document.getElementById("frmMain").action = "administration.TasksAction.do?action=confirm";
				submitForm(document.getElementById("frmMain"));
			}
		}
	}
}
function btnExit_click(){
	var msg = confirm(GNR_PER_DAT_ING);
	if (msg) {
		splash();
	}
}
function btnBack_click() {
	if (canWrite()){
		var msg = confirm(GNR_PER_DAT_ING);
		if (msg) {
			document.getElementById("frmMain").action = "administration.TasksAction.do?action=backToList";
			submitForm(document.getElementById("frmMain"));
		}
	}else{
		document.getElementById("frmMain").action = "administration.TasksAction.do?action=backToList";
		submitForm(document.getElementById("frmMain"));
	}
}

//---------------------------------------------------
//------------   FUNCIONES PARA POOLS   -------------
//---------------------------------------------------
function btnAddPool_click() {
	var rets = openModal("/programs/modals/pools.jsp?showAutogenerated=true&showOnlyEnv=true&envId=" + ENV_ID + "&showGlobal=true",500,350);
	var doAfter=function(rets){
		if (rets != null) {
			for (j = 0; j < rets.length; j++) {
				var ret = rets[j];
				var addRet = true;
				
				trows=document.getElementById("gridPools").rows;
				for (i=0;i<trows.length && addRet;i++) {
					if (trows[i].getElementsByTagName("TD")[0].getElementsByTagName("INPUT")[1].value == ret[0]) {
						addRet = false;
					}
				}
				
				if (addRet) {
					var oTd0 = document.createElement("TD"); 
					var oTd1 = document.createElement("TD"); 
					
					oTd0.innerHTML = "<input type='checkbox' name='chkPoolSel'><input type='hidden' name='idPool'><input type='hidden' name='txtPool'>";
					oTd0.getElementsByTagName("INPUT")[1].value = ret[0];
					oTd0.getElementsByTagName("INPUT")[2].value = ret[1];
					oTd0.align="center";
					
					oTd1.innerHTML = ret[1];
					
					var oTr = document.createElement("TR");
					oTr.appendChild(oTd0);
					oTr.appendChild(oTd1);
					document.getElementById("gridPools").addRow(oTr);
				}
			}
		}
	}
	rets.onclose=function(){
		doAfter(rets.returnValue);
	}
	/*if (window.navigator.appVersion.indexOf("MSIE")<0){
		var aux=rets.document;
		var isOpen=true;
		rets.onunload=function(event){
			event.cancelBubble=true;
			if(!isOpen){
				doAfter(rets.returnValue);
			}
			isOpen=false;
	    }
    }else{
		doAfter(rets);
	}*/
}

function btnDelPool_click() {
	document.getElementById("gridPools").removeSelected();
}
//------------------------------------------------
//---- Funcione para trabajar con las alertas
//------------------------------------------------

function btnConfPools_click(event) {
	document.getElementById("frmMain").action = "administration.TasksAction.do?action=addPools&event=" + EVENT;
	submitFormModal(document.getElementById("frmMain"));
}	

function btnExitPools_click() {
	window.returnValue=null;
	window.close();
}

function alterPools(event) {
	//openModal("/programs/administration/tasks/pools.jsp?event=" + event,500,500);
	openModal("/administration.TasksAction.do?action=alterPools&event=" + event + windowId,500,500);
}

function alterMessage(event) {
	//openModal("/programs/administration/tasks/message.jsp?event=" + event,500,350);
	openModal("/administration.TasksAction.do?action=alertMessage&event=" + event + windowId,500,500);
}

//---------------------------------------------------
//-----------  FUNCIONES PARA MENSAJES  -------------
//---------------------------------------------------

function btnConfMessage_click() {
	document.getElementById("frmMain").action = "administration.TasksAction.do?action=alterMessage&event=" + EVENT;
	submitFormModal(document.getElementById("frmMain"));
}	

function btnExitMessage_click() {
	window.returnValue=null;
	window.close();
}

function btnDefMessage_click() {
	document.getElementById("txtMes").value = DEFAULT_MESSAGE;
}

//---------------------------------------------------
//------------  FUNCIONES PARA ALERTAS  -------------
//---------------------------------------------------
function cmbAlert_change(type) {
	if (document.getElementById(type).value == '0') {
		document.getElementById(type+'L').style.visibility = "";
		document.getElementById(type+'L').p_required = "true";
	} else {
		document.getElementById(type+'L').style.visibility = "hidden";
		document.getElementById(type+'L').value = '0';
	}
}

function customKeyPress(){
	if (document.getElementById("customTemplate") != null) {
		if(document.getElementById("customTemplate").value!=""){
			document.getElementById("btnVerTwo").disabled = false;
		} else {
			document.getElementById("btnVerTwo").disabled = true;
		}
	}
}

function changeTemplate() {
/// se hace el try poruqe este js se llama en la funcionalidad y tambien en el modal de pools que no tiene el campo customTemplate
try{
	if (document.getElementById("txtTemplate").value=="<CUSTOM>") {
		document.getElementById("btnVerOne").style.display = "none";
		document.getElementById("customTemplate").disabled=false;
		document.getElementById("customTemplate").style.visibility = "";
		document.getElementById("btnVerTwo").style.visibility = "";		
		document.getElementById("btnVerTwo").disabled = true;
	} else if (!document.getElementById("customTemplate").disabled) {
		document.getElementById("customTemplate").value = "";
		document.getElementById("btnVerOne").style.display = "";
		document.getElementById("customTemplate").disabled=true;
		document.getElementById("customTemplate").style.visibility = "hidden";
		document.getElementById("btnVerTwo").style.visibility = "hidden";	
		document.getElementById("btnVerTwo").disabled = true;	
	}
	
	document.getElementById("btnVerOne").disabled = document.getElementById("txtTemplate").selectedIndex == 0;
} catch (e) {}
}

function btnViewTemplate() {
    tmpl = document.getElementById("txtTemplate").value;

	if (document.getElementById("txtTemplate").selectedIndex == document.getElementById("txtTemplate").options.length-1) {
		tmpl = document.getElementById("customTemplate").value;
	}

    if (tmpl == "") {
	    tmpl = "/templates/taskDefault.jsp";
    }
    
	openModal("/programs/modals/templateTest.jsp?template="+escape(tmpl),600,500);
}

function openImagePicker(caller){
	var rets = openModal("/administration.ImagesAction.do?action=picker",560,300);
	var doAfter=function(rets){
		if(rets && rets.path && rets.id){
			var path=rets.path;
			var id=rets.id;
			caller.style.backgroundImage="url("+path+")";
			caller.firstChild.value=id;
		}else{
			caller.firstChild.value="";
			caller.style.backgroundImage="url("+URL_ROOT_PATH+"/images/uploaded/taskicon.png)";
		}
	}
	rets.onclose=function(){
		doAfter(rets.returnValue);
	}
}

function verifyPermissions(){
	if (!document.getElementById("usePrjPerms").checked){ //Si no se usan los permisos del proyecto
		//Verificamos si almenos una persona tiene acceso de modificacion
		var permRows=document.getElementById("permGrid").rows;
		var someoneCanModify = false;
		for(var i=0;i<permRows.length;i++){
			var canModify= ("1" == permRows[i].getElementsByTagName("TD")[0].getElementsByTagName("INPUT")[3].value);
			if(canModify){//Verificamos que los nombres de los atributos no sean nulos
				someoneCanModify = true;
			}
		}
		if (!someoneCanModify){
			alert(MSG_PERMISSIONS_ERROR);	
			return false;
		}
	}
	return true;
}

function canWrite(){
	var usrCanWrite = document.getElementById("hidUsrCanWrite").value;
	if (usrCanWrite=='true'){
		return true;
	}else{
		return false;	
	}
}

function cmbProySel(){
	if (document.getElementById("selPrj").value == "0"){
		//Deshabilitamos el checkbox de usar permisos del proyecto
		document.getElementById("usePrjPerms").checked = false;
		document.getElementById("usePrjPerms").disabled = true;
		//Habilitamos la grilla de permisos
		document.getElementById("permGrid").disabled = false;
		document.getElementById("addPoolUsrPerm").disabled = false;
		document.getElementById("delPoolUsrPerm").disabled = false;
		//Vaciamos la grilla de permisos, dejando TODOS clickeado
		//delAllPerms(true);
		var oRows = document.getElementById("permGrid").rows;
		var td = oRows[0].getElementsByTagName("TD");
		//Marcamos el modo lectura
		td[3].getElementsByTagName("INPUT")[0].checked = true;
		td[0].getElementsByTagName("INPUT")[2].value = 1;
		//Marcamos escritura
		td[3].getElementsByTagName("INPUT")[1].checked = true;
	 	td[0].getElementsByTagName("INPUT")[3].value = 1;
	}else{
		//Habilitamos el checkbox de usar permisos del proyecto	
		document.getElementById("usePrjPerms").disabled = false;
		//Cargamos la grilla con los permisos del proyecto
		//loadProyectPerms(); <--- TODO, SI SE HACE SE DEBE HACER PARA TODOS LOS OBJETOS DE DISEÑO
		if (!document.getElementById("usePrjPerms").checked){ //Si no esta clickeado el checkbox de usar los permisos del proyecto
			var msg = confirm(MSG_USE_PROY_PERMS);
			if (msg) {
				document.getElementById("usePrjPerms").checked = true;
				//Deshabilitamos la grilla de permisos
				document.getElementById("permGrid").disabled = true;
				document.getElementById("addPoolUsrPerm").disabled = true;
				document.getElementById("delPoolUsrPerm").disabled = true;
				//Vaciamos la grilla de permisos, dejando TODOS sin clickear
				delAllPerms(false);
			}
		}
	}
}

function loadProyectPerms(){
	//1. Obtenemos el id del proyecto seleccionado
	var prjId = document.getElementById("selPrj").value;
	var sXMLSourceUrl = "administration.TasksAction.do?action=getProjPermssions&prjId=" + prjId;
	var xmlLoad=new xmlLoader();
	xmlLoad.onload=function(xmlRoot){
	
		for(i=0;i<xmlRoot.childNodes.length;i++){
			xRow = xmlRoot.childNodes[i];
			var option = document.createElement("OPTION");
			
			/* TODO */
		
		}
	}
	xmlLoad.load(sXMLSourceUrl);
}
