<%@page import="com.dogma.vo.*"%><%@include file="../../../components/scripts/server/startInc.jsp" %><%@include file="../../../components/scripts/server/headInclude.jsp" %><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.security.MigrationBean"/><%
EnvironmentVo envVo = dBean.getEnvVo();
%><HTML><head></head><body><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,"titMigEnv")%></TD><TD></TD></TR></TABLE><div id="divContent"><form id="frmMain" name="frmMain" method="POST"><!--      Environment Data (Show basic VO data)													         --><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtMigExpData")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td><%=LabelManager.getName(labelSet,"lblMigEnvId")%>:</td><td><%=envVo.getEnvId()%></td><td><%=LabelManager.getName(labelSet,"lblMigEnvName")%>:</td><td><%=envVo.getEnvName()%></td></tr></table><br><br><!--       Export target destination															         --><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtMigExpTarget")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td title="<%=LabelManager.getName(labelSet,"lblMigExpFile")%>"><%=LabelManager.getName(labelSet,"lblMigExpFile")%>:</td><%
						if (!dBean.isExportDone()) {
							String expFileName = com.st.util.StringUtil.replace("export_" + envVo.getEnvName(), " ", "_");
							expFileName = com.st.util.StringUtil.replace(expFileName, "[", "");
							expFileName = com.st.util.StringUtil.replace(expFileName, "]", "");
							expFileName = com.st.util.StringUtil.replace(expFileName, "\n", ""); %><td colspan="3"><input type="text" name="tbxExpFile" size="50" value="<%=expFileName%>"></td><%
						} else {
							String expFileName = dBean.getExportFileName(); %><td colspan="3"><%=expFileName%></td><%
						} %></tr><tr><td title="<%=LabelManager.getName(labelSet,"lblMigExpClaFile")%>"><%=LabelManager.getName(labelSet,"lblMigExpClaFile")%>:</td><td colspan="3"><input name="chkExpClassFile" type="checkbox" value="true" <%= dBean.isExportClassesFiles()?"checked":"" %><%= dBean.isExportDone()?"disabled":"" %>></td></tr><tr><td title="<%=LabelManager.getName(labelSet,"lblMigExpJsFile")%>"><%=LabelManager.getName(labelSet,"lblMigExpJsFile")%>:</td><td colspan="3"><input name="chkExpJSFile" type="checkbox" value="true" <%= dBean.isExportJSFiles()?"checked":"" %><%= dBean.isExportDone()?"disabled":"" %>></td></tr></table><!--       Export file generated  															         --><% if (dBean.isExportDone()) { %><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtMigExpFile")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td align="left">&nbsp;</td><td colspan="3" align="left"><button type="button" onclick="btnDownload_click()" title="<%=LabelManager.getName(labelSet,"lblMigDownloadFile")%>"><%=LabelManager.getName(labelSet,"lblMigDownloadFile")%></button></td></tr><tr><td colspan="4"><iframe id="downloadIFrame" name="downloadIFrame"
								        src="<%=request.getContextPath()%>/programs/security/migration/download/download.jsp" 
								        style="visibility:hidden"></iframe></td></tr></table><%
				} %></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD><% if (!dBean.isExportDone()) {%><button type="button" onclick="btnAnt_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnAnt")%>" title="<%=LabelManager.getToolTip(labelSet,"btnAnt")%>"><%=LabelManager.getNameWAccess(labelSet,"btnAnt")%></button><button type="button" onclick="btnCon_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnCon")%>" title="<%=LabelManager.getToolTip(labelSet,"btnCon")%>"><%=LabelManager.getNameWAccess(labelSet,"btnCon")%></button><iframe id="iframeKeepActive" style="display:none"></iframe><% } %><button type="button" onclick="btnVol_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnVol")%>" title="<%=LabelManager.getToolTip(labelSet,"btnVol")%>"><%=LabelManager.getNameWAccess(labelSet,"btnVol")%></button><button type="button" onclick="btnSal_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><!--     Auxiliary inclusion end (Constants, parameters, etc)								         --><%@include file="../../../components/scripts/server/endInc.jsp" %><script language="javascript" src='<%=Parameters.ROOT_PATH%>/programs/security/migration/exportstep3.js'></script>

