<%@page import="com.dogma.vo.*"%><%@page import="com.dogma.vo.filter.*"%><%@page import="java.util.*"%><%@page import="com.dogma.bean.query.MonitorProcessesBean"%><%@include file="../../../components/scripts/server/startInc.jsp" %><HTML><head><%@include file="../../../components/scripts/server/headInclude.jsp" %></head><body><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.execution.ProRollbackBean"></jsp:useBean><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><%if (dBean.TYPE_ADHOC.equals(dBean.getRollbackType())) {%><TD><%=LabelManager.getName(labelSet,"titAdhoc")%></TD><%} else {%><TD><%=LabelManager.getName(labelSet,"titProRol")%></TD><%}%><TD></TD></TR></TABLE><DIV id="divContent" class="divContent"><form id="frmMain" name="frmMain" method="POST"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtMonTsk")%></DIV><div type="grid" id="gridList" style="height:<%=Parameters.SCREEN_LIST_SIZE%>px"><table width="500px" cellpadding="0" cellspacing="0"><thead><tr><th style="width:0px;display:none;">&nbsp;</th><th min_width="110px" style="min-width:110px;width:100%" title="<%=LabelManager.getToolTip(labelSet,"lblMonTskNom")%>"><%=LabelManager.getName(labelSet,"lblMonTskNom")%></th><th min_width="90px" style="width:90px" title="<%=LabelManager.getToolTip(labelSet,"lblMonPoolNom")%>"><%=LabelManager.getName(labelSet,"lblMonPoolNom")%></th><th min_width="80px" style="width:80px" title="<%=LabelManager.getToolTip(labelSet,"lblMonProEleInstSta")%>"><%=LabelManager.getName(labelSet,"lblMonProEleInstSta")%></th><th min_width="105px" style="width:105px" title="<%=LabelManager.getToolTip(labelSet,"lblMonProEleInstDatRea")%>"><%=LabelManager.getName(labelSet,"lblMonProEleInstDatRea")%></th><th min_width="105px" style="width:105px" title="<%=LabelManager.getToolTip(labelSet,"lblMonProEleInstDatEnd")%>"><%=LabelManager.getName(labelSet,"lblMonProEleInstDatEnd")%></th><th min_width="100px" style="width:100px" title="<%=LabelManager.getToolTip(labelSet,"lblMonUsrLog")%>"><%=LabelManager.getName(labelSet,"lblMonUsrLog")%></th></tr></thead><tbody><%	Collection col = dBean.getProInstTasks();
							if (col != null) {
								Iterator it = col.iterator();
								int i = 0;
								MonitorTaskVo mPITVo;
								Integer oldProEleInstId = null;
								while (it.hasNext()) {
									mPITVo = (MonitorTaskVo) it.next(); 
									%><tr><td style="width:0px;display:none;"><%System.out.println("ALIVE "+mPITVo.isAlive()+" "+mPITVo.getProEleInstId()); %><%if (dBean.TYPE_ADHOC.equals(dBean.getRollbackType())) {%><input type="hidden" name="selected<%=i%>" <% if (mPITVo.getProEleInstId() == null || !mPITVo.isAlive()) {%> style="visibility:hidden;"<%}%>><input type="hidden" name="chkSel<%=i%>" value="<%=mPITVo.getProInstEleIdFather() == null?  dBean.fmtInt(mPITVo.getProEleInstId()):dBean.fmtInt(mPITVo.getProInstEleIdFather())%>" onclick="chkSelected(this, <%= mPITVo.isAlive() ?"false":"true"%>)"><%} else {%><input type="hidden" name="selected<%=i%>" <% if (mPITVo.getProEleInstId() == null || mPITVo.isAlive()) {%> style="visibility:hidden;"<%}%>><input type="hidden" name="chkSel<%=i%>" value="<%=dBean.fmtInt(mPITVo.getProEleInstId())%>" onclick="chkSelected(this, <%= mPITVo.isAlive() ?"false":"true"%>)"><%}%></td><td style="min-width:110px" <%=mPITVo.isLate()?" class=\"tdProLat\"":mPITVo.isInAlert()?" class=\"tdProInAle\"":""%>><%=dBean.fmtHTML(mPITVo.getTskName())%></td><td<%=mPITVo.isLate()?" class=\"tdProLat\"":mPITVo.isInAlert()?" class=\"tdProInAle\"":""%>><%=dBean.fmtHTML(mPITVo.getPoolName())%></td><% if (mPITVo.getPoolName() == null) {%><td<%=mPITVo.isLate()?" class=\"tdProLat\"":mPITVo.isInAlert()?" class=\"tdProInAle\"":""%>><a href="execution.ProRollbackAction.do?action=tasks&proInstId=<%=mPITVo.getProEleInstId()%>" ><%=dBean.fmtHTML(mPITVo.getTskName())%></a></td><% } else {%><td<%=mPITVo.isLate()?" class=\"tdProLat\"":mPITVo.isInAlert()?" class=\"tdProInAle\"":""%>><%=ProEleInstanceVo.ELE_STATUS_WAITING.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaWai"):
											ProEleInstanceVo.ELE_STATUS_READY.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaRea"):
											ProEleInstanceVo.ELE_STATUS_ACQUIRED.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaAcq"):
											ProEleInstanceVo.ELE_STATUS_COMPLETED.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaCom"):
											ProEleInstanceVo.ELE_STATUS_UNDO.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaCom"):
											ProEleInstanceVo.ELE_STATUS_CANCELLED.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaCan"):
											ProEleInstanceVo.ELE_STATUS_ROLLBACK.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaRol"):
											ProEleInstanceVo.ELE_STATUS_SKIPPED.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaSki"):""%></td><%}%><td<%=mPITVo.isLate()?" class=\"tdProLat\"":mPITVo.isInAlert()?" class=\"tdProInAle\"":""%>><%=dBean.fmtHTMLAMPM(mPITVo.getProEleInstDateReady())%></td><td<%=mPITVo.isLate()?" class=\"tdProLat\"":mPITVo.isInAlert()?" class=\"tdProInAle\"":""%>><%=dBean.fmtHTMLAMPM(mPITVo.getProEleInstDateEnd())%></td><td<%=mPITVo.isLate()?" class=\"tdProLat\"":mPITVo.isInAlert()?" class=\"tdProInAle\"":""%>><%=dBean.fmtHTML(mPITVo.getUsrLogin())%></td></tr><%
									i++;
								}
							}%></tbody></table></div></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD><button type="button" onclick="btnBack_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnMonBack")%>" title="<%=LabelManager.getToolTip(labelSet,"btnMonBack")%>"><%=LabelManager.getNameWAccess(labelSet,"btnMonBack")%></button><%if (dBean.TYPE_ADHOC.equals(dBean.getRollbackType())) {%><button type="button" id=btnAdHoc onclick="btnAdHoc_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSig")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSig")%>" ><%=LabelManager.getNameWAccess(labelSet,"btnSig")%></button><%} else {%><button type="button" id=btnRoll onclick="btnRoll_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSig")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSig")%>" ><%=LabelManager.getNameWAccess(labelSet,"btnSig")%></button><%}%><button type="button" onclick="splash()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><%@include file="../../../components/scripts/server/endInc.jsp" %><script language="javascript" src='<%=Parameters.ROOT_PATH%>/programs/execution/proRollback/rollback.js'></script>