<script type="text/javascript">
	var URL_REQUEST_AJAX_CALENDAR = '/apia.modals.CalendarViewAction.run';
	var SUNDAY 		= '<system:label show="text" label="lblDomingo" forScript="true" />';
	var MONDAY 		= '<system:label show="text" label="lblLunes" forScript="true" />';
	var TUESDAY 	= '<system:label show="text" label="lblMartes" forScript="true" />';
	var WEDNESDAY 	= '<system:label show="text" label="lblMiercoles" forScript="true" />';
	var THURSDAY 	= '<system:label show="text" label="lblJueves" forScript="true" />';
	var FRIDAY 		= '<system:label show="text" label="lblViernes" forScript="true" />';
	var SATURDAY 	= '<system:label show="text" label="lblSabado" forScript="true" />';
	var LBL_A		= '<system:label show="text" label="lblA" forScript="true" />';
</script><system:edit show="ifModalNotLoaded" field="calendars.jsp"><system:edit show="markModalAsLoaded" field="calendars.jsp" /><div id="mdlCalendarViewContainer" class="mdlContainer hiddenModal"><div class="mdlHeader"><system:label show="text" label="titCal" /></div><div class="mdlBody" id="mdlBody"><div class="fieldGroup"><div class="title"><system:label show="text" label="txtAnaGenData" /></div><div class="field" id="calName"><label title="<system:label show="tooltip" label="lblNom" />"><system:label show="text" label="lblNom" />:</label></div><div class="field extendedSize" id="calDesc"><label title="<system:label show="tooltip" label="lblDes" />"><system:label show="text" label="lblDes" />:</label></div></div><div class="fieldGroup"><div class="title"><system:label show="text" label="sbtDatDayLab" /></div></div><div class="gridHeader gridHeaderModal"><!-- Cabezal y filtros --><table cellpadding="0" cellspacing="0"><thead><tr id="trOrderBy" class="header"><th title="<system:label show="tooltip" label="lblBIDay" />"><div style="width:200px"><system:label show="text" label="lblBIDay" /></div></th><th title="<system:label show="tooltip" label="lblHorario" />"><div style="width:260px"><system:label show="text" label="lblHorario" /></div></th></tr></thead></table></div><div class="gridBody gridBodyModal" id="mdlGridBody" style="overflow-x: hidden !important; height: 150px;"><!-- Cuerpo de la tabla --><table cellpadding="0" cellspacing="0"><thead><tr><th width="200px"></th><th width="259px"></th></tr></thead><tbody class="tableData" id="tableDataDays"></tbody></table></div><div class="fieldGroup"><div class="title"><system:label show="text" label="lblFerDay" /></div><div class="field" style="width:100%"><div class="modalOptionsContainer" id="freeDaysContainter"></div></div></div></div><div class="gridFooter"><div class="navButtonsOptions"><div class="navButton" id="closeModalCalView" style="width: 40px"><system:label show="text" label="lblCloseWindow" /></div></div></div></div></system:edit>