var usePrjPerms;

function initTskSchPermissions(mode) {
	usePrjPerms = $('usePrjPerms');
	var cmbProject = $('selPrj');
	var prmAddPool = $('prmAddPool');
	
	if (prmAddPool) {
		prmAddPool.addEvent("click", function(e) {
			e.stop();
			//setear variables de configuracion del modal de grupos
			POOLMODAL_SHOWAUTOGENERATED = false;
			ADDITIONAL_INFO_IN_TABLE_DATA = false;
			//abrir modal
			showPoolsModal(prmTskSchProcessPoolsModalReturn);
		});
	}
	
	if (cmbProject) {
		cmbProject.usePrjPerms = usePrjPerms;
		cmbProject.prmAddPool = prmAddPool;
		cmbProject.addEvent('change', function(etv){
			if (this.selectedIndex == 0) {
				this.usePrjPerms.checked = false;
				this.usePrjPerms.disabled = true;
				prmAddPool.style.display = '';
			} else {
				this.usePrjPerms.disabled = false;
				showConfirm(MSG_USE_PROY_PERMS,GNR_TIT_WARNING,changeProjectConfirm,"modalWarning");
				
			}
		});
	} else {
		usePrjPerms.disabled = true;
	}
	
	usePrjPerms.addEvent('click', function(evt){
		if (this.checked) {
			showConfirm(MSG_PERM_WILL_BE_LOST,GNR_TIT_WARNING,changePrjPermConfirm,"modalWarning");
			
			
		} else {
			//1. Habilitamos el combo de lectura/modificacion para todos
			//selPerAllPoolPermRW.disabled = false;
			//2. Habilitamos los combos de lectura/modificacion para cada grupo
			$('prmPoolContainter').getElements('div.list-item').each(function (div) {
				var sel = div.getElements('select');
				if(sel && sel.length > 0)
					sel.each(function(s) {s.erase('disabled')});
			});
		}
	});
	
	
	initPoolMdlPage();
	loadPermissions(mode);
}

function changePrjPermConf(result){
	var prmAddPool = $('prmAddPool');
	var cmbProject = $('cmbProject');
	if (result) {
		//1- Deshabilitamos el combo de lectura/modificaci�n para todos y seleccionamos el index 0
		//selPerAllPoolPermRW.selectedIndex = 0;
		//selPerAllPoolPermRW.disabled = true; 
		
		//2. Deshabilitamos todos los combos de lectura/modificacion para grupos y seleccionamos el index 0
		$('prmPoolContainter').getElements('div.list-item').each(function (div) {
			var sel = div.getElements('select');
			if(sel) {
				sel[1].set('value', 0);
				sel[1].set('disabled', true);
			}
		});
		
	} else {
		//Descliqueamos el checkbox
		cmbProject.checked = false;
	}
}

function changeProjectConfirm(result){
	var prmAddPool = $('prmAddPool');
	var usePrjPerms = $('usePrjPerms');
	if (result) {
		usePrjPerms.checked = true;
		$('prmPoolContainter').getElements('div').each(function (div) {
			var sel = div.getElements('select')[0];
			if(sel) {
				sel.set('value', 0);
				sel.set('disabled', true);
			}
		});
		
	} else {
		usePrjPerms.checked = false;
		$('prmPoolContainter').getElements('div').each(function (div) {
			//div.getElements('select')[0].erase('disabled');
			var sel = div.getElements('select')[0];
			if(sel) {
				sel.erase('disabled');
			}
		});
	}
}

function loadPermissions(mode) {
	var request = new Request({
		method: 'post',
		url: CONTEXT + URL_REQUEST_AJAX + '?action=loadTskSchPermissions&isAjax=true' + TAB_ID_REQUEST,
		onRequest: function() { },
		onComplete: function(resText, resXml) { 
			processXMLPerms(resXml,mode);
			
			initAdminModalHandlerOnChangeHighlight($('prmPoolContainter'), true);
			
			$('prmAddPool').grab(new Element('div', {id : 'editionNot'}), "bottom");
			
		}
	}).send();
}

function processXMLPerms(ajaxCallXml,mode){
	if (ajaxCallXml != null) {
		var atts = ajaxCallXml.getElementsByTagName("perms");
		if (atts != null && atts.length > 0 && atts.item(0) != null) {
			atts = atts.item(0).getElementsByTagName("perm");
			for(var i = 0; i < atts.length; i++) {
				var att = atts.item(i);
				
				var user = att.getAttribute("user");
				var pool_id = att.getAttribute("pool_id");
				var pool_name = att.getAttribute("pool_name");
				var perms = att.getAttribute("perms");
			
				addPermssionToContainer(user, pool_id, pool_name, perms, i);
			}
			
			if (mode == INSERT_MODE){
				if ($('selPrj').selectedIndex == 0){ //Si no se esta usando proyecto
					$('usePrjPerms').disabled = true; //Deshabilitamos checkbox de usar permisos del proyecto
				}
				$('selPerAllPoolPermRW').selectedIndex = 2; //Seleccionamos leer y modificar para todos
				$('selPerAllPoolPermQR').selectedIndex = 3; //Seleccionamos consultar y reagendar para todos
			}
		}
	}
}

function prmTskSchProcessPoolsModalReturn(ret) {
	ret.each(function(e){
		var text = e.getRowContent()[0];
		var id = e.getRowId();
		
		if (id==null){
			addPermssionToContainer(text, null, null, '', true);
		}else {
			addPermssionToContainer(null, id, text, '', true);
		}
		
	});
}

function addPermssionToContainer(user, pool_id, pool_name, perms, deletable) {
	var name = "ALL";
	var id = "ALL";
	
	if (user!=null){
		name = user;
		id = user;
	}
	if (pool_id!=null){
		name = pool_name;
		id = pool_id;
	}
	
	var read="";
	var write="";
	var query="";
	var resched="";
	
	if (perms.substring(0,1)=='1') read = "selected";
	if (perms.substring(1,2)=='1') {
		read="";
		write = "selected";
	}
	if (perms.substring(2,3)=='1') query = "selected";
	if (perms.substring(3,4)=='1') {
		query="";
		resched = "selected";
	}
	
	var ele1 = new Element('div.min_text').set({
		'html': '<span>' + name + '</span>'
	}).setStyle('width', 400).set('title', name);
	
	var ele2 = new Element('select', {
		name: deletable ? 'selPerPoolPermRW' : 'selPerAllPoolPermRW', 
		id: deletable ? 'selPerPoolPermRW' : 'selPerAllPoolPermRW',		
		html: '<option value="0">' + ACCESS_PERM_0 + '</option><option value="1" ' + read + '>' + ACCESS_PERM_1 + '</option><option value="2" ' + write + '>' + ACCESS_PERM_2 + '</option>'
	}).setStyle('width', 150);
	
	var ele3 = new Element('select', {
		name:  deletable ? 'selPerPoolPermQR' : 'selPerAllPoolPermQR', 
		id: deletable ? 'selPerPoolPermQR' : 'selPerAllPoolPermQR', 
		html: '<option value="0">' + SCHED_PERM_0 + '</option><option value="1" ' + query + '>' + SCHED_PERM_1 + '</option><option value="2" ' + resched + '>' + SCHED_PERM_2 + '</option>'		
	}).setStyle('width', 150);
	
	if($('usePrjPerms').get('checked')) {
		ele2.set('disabled', 'true');
		//ele3.set('disabled', 'true');
	}
	
	if(deletable) {
		var ele4 = new Element('input', {
			name: 'hidPerPoolId', 
			id: 'hidPerPoolId', 
			value: pool_id,
			type: 'hidden'
		}).setStyle('display', 'none');
		
		Generic.createListItem(deletable, ele1, ele2, ele3, ele4).inject($('prmPoolContainter')).addEvent('crossclicked', function() {
			this.dispose();
		});
	} else {
		Generic.createListItem(deletable, ele1, ele2, ele3).inject($('prmPoolContainter')).addEvent('crossclicked', function() {
			this.dispose();
		});
	}
}

function validatePerms(el){ //Al menos un usuario debe tener permiso de modificacion en la agenda
	var container = $('prmPoolContainter');
	var selected = 0;
	if ($("selPerAllPoolPermRW").value > 1) return true;
	
	for (var i = 1; i < container.getElementsByTagName("select").length; i=i+2){
		var sel = container.getElementsByTagName("select")[i];
		if (sel.value > 1) return true;
	}

	el.errors.push(MSG_SCH_PRIV_ERROR);
    return false;

}

