function initPermissionsTab(mode) {

	//Configuramos acción del botón de agregar permisos
	if ($('prmAddPool')) { 
		$('prmAddPool').addEvent("click", function(e) {
			e.stop();
			//setear variables de configuracion del modal de grupos
			POOLMODAL_SHOWAUTOGENERATED = true;
			POOLMODAL_SHOWNOTAUTOGENERATED = true;
			POOLMODAL_SHOWGLOBAL = true;
			POOLMODAL_SHOWCURRENTENV = true;
			ADDITIONAL_INFO_IN_TABLE_DATA = false;
			//abrir modal
			showPoolsModal(prmProcessPoolsModalReturn);
		});
	}
	
	//initPoolMdlPage(); //Para el modal de selección de grupos
	
	loadPermissions(); //Cargamos los grupos con los permisos
	
	
}

//Procesa resultado del modal para seleccionar grupos para asignar permisos
function prmProcessPoolsModalReturn(ret) {
	ret.each(function(e){
		var poolName = e.getRowContent()[0];
		var poolId = e.getRowId();
		
		addPermissionToContainer(poolName, poolId);
	});
}


//Carga los permisos con acceso de edición sobre el widget
function loadPermissions() {
	var request = new Request({
		method: 'post',
		url: CONTEXT + URL_REQUEST_AJAX + '?action=loadWidgetPermissions&isAjax=true' + TAB_ID_REQUEST,
		onRequest: function() { },
		onComplete: function(resText, resXml) { processXMLPerms(resXml); }
	}).send();
}

//Procesa el XML con los permisos de edición sobre el cubo
function processXMLPerms(ajaxCallXml){
	if (ajaxCallXml != null) {
		var atts = ajaxCallXml.getElementsByTagName("perms");
		if (atts != null && atts.length > 0 && atts.item(0) != null) {
			atts = atts.item(0).getElementsByTagName("perm");
			for(var i = 0; i < atts.length; i++) {
				var att = atts.item(i);
				
				var pool_id = att.getAttribute("pool_id");
				var pool_name = att.getAttribute("pool_name");
				var perms = att.getAttribute("perms");
			
				addPermissionToContainer(pool_name, pool_id, perms);
			}
		}
	}
}

//Agrega un grupo en el container de permisos 
function addPermissionToContainer(poolName, poolId, perms) {
	var content;
	
	if(poolId == -1) content = addActionElementAdmin($('divPools'), poolName + " ", poolId, "false", false, "hidPerPoolId");
	else content = addActionElement($('divPools'),poolName + " ", poolId, "hidPerPoolId");
	
	if (content == null) return;
	
	var noPerm = "";
	var readPerm = "";
	var writePerm = "";
	
	if (perms=="R"){
		readPerm = "selected";
	}else if (perms=="RW"){
		writePerm = "selected";
	}else {
		noPerm = "selected";
	}
	
	var ele2 = new Element('select', {
		name:'selPerPoolPermRW', 
		id: 'selPerPoolPermRW',		
		html: '<option value="0"' + noPerm + '></option><option value="1"' + readPerm + '>' + 'Leer' + '</option><option value="2"' + writePerm + '>' + 'Leer y modificar' + '</option>'
	}).setStyle('width', 150).addEvent('click', function (e) {
		e.stopPropagation();
	});
	ele2.addClass("validate['~validatePerms']");
	ele2.inject(content);
	
	$('frmData').formChecker.register(ele2,1);
}

//Validación de permisos
function validatePerms(el){ //Al menos un usuario debe tener permiso de modificacion en el widget
	var container = $('divPools');
	
	for (var i = 0; i < container.getElementsByTagName("select").length; i=i+1){
		var sel = container.getElementsByTagName("select")[i];
		if (sel.value > 1) return true;
	}

	el.errors.push(MSG_CUBE_PRIV_ERRORS);
    return false;

}