<%@page import="java.util.*"%><%@include file="../../../components/scripts/server/startInc.jsp" %><%@page import="com.dogma.vo.WsPublicationVo"%><%@page import="com.dogma.vo.WsTreeVo"%><%@page import="com.dogma.vo.UserVo"%><HTML><head><%@include file="../../../components/scripts/server/headInclude.jsp" %></head><body><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.configuration.WsBean"></jsp:useBean><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,"titWs")%></TD><TD></TD></TR></TABLE><%int i = 0; %><DIV id="divContent" class="divContent"><form id="frmMain" name="frmMain" method="POST"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtWs")%></DIV><div style="height: 200px;" type="grid" id="gridList" docBean=""><table cellpadding="0" cellspacing="0"><thead class="fixedHeader"><tr><th min_width="30px" style="width:30px" title="<%=LabelManager.getToolTip(labelSet,"lblWsStatus")%>"><%=LabelManager.getName(labelSet,"lblWsStatus")%></th><th min_width="100px" style="min-width:100px;width:50%" title="<%=LabelManager.getToolTip(labelSet,"lblWsPro")%>"><%=LabelManager.getName(labelSet,"lblWsPro")%></th><th min_width="100px" style="min-width:100px;width:50%" title="<%=LabelManager.getToolTip(labelSet,"lblWsTsk")%>"><%=LabelManager.getName(labelSet,"lblWsTsk")%></th><th min_width="20px" style="width:20px" title="WSS">WSS</th><th min_width="180px" style="width:180px" title="User">User</th><th min_width="80px" style="width:80px" title="<%=LabelManager.getToolTip(labelSet,"lblWsAct")%>"><%=LabelManager.getName(labelSet,"lblWsAct")%></th></tr></thead><tbody class="scrollContent"><%	Collection col = dBean.getProWS(uData);
							if (col != null) {
								Iterator it = col.iterator();
								
								WsTreeVo wsTreeVo = null;
								WsPublicationVo wsPubVo;
								while (it.hasNext()) {
									wsTreeVo = (WsTreeVo)it.next(); 
									if(wsTreeVo.getWsPublicationVo() != null){
										wsPubVo = wsTreeVo.getWsPublicationVo();
									
										if(wsPubVo.getWsName()!=null && wsPubVo.getWsName() != ""){%><tr><%if(wsPubVo.getStatus() == null){%><td></td><%}else{%><td align="center"><img src="<%if(wsPubVo.getStatus().equals(WsPublicationVo.STATUS_PUBLISHED_NOT_OK)){
															out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority1.gif");
														}else if(wsPubVo.getStatus().equals(WsPublicationVo.STATUS_PUBLISHED_OK)){
															out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority2.gif");
														}else{
															out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority3.gif");
														}%>"></td><%} %><td style="min-width:100px"><%=wsPubVo.getWsName()%> (<%=wsPubVo.getEnvName()%>)</td><td style="min-width:100px"></td><td><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><input type="checkbox" id="chkWss<%=i%>" onclick="chkWSSClick(this,<%=i%>)" <%if("1".equals(wsPubVo.getWss())){out.print(" checked ");}%>><%}else{ %><input type="checkbox" id="chkWss<%=i%>" onclick="this.checked=<%if("1".equals(wsPubVo.getWss())){out.print("true");}else{out.print("false");}%>" <%if("1".equals(wsPubVo.getWss())){out.print(" checked ");}%>><%} %></td><td><input id="txtUsu<%=i%>" name="txtUsu<%=i%>" size="25"  value="<%=wsPubVo.getWssUser()!=null?wsPubVo.getWssUser():""%>" readonly class="txtReadOnly" <%if(!"1".equals(wsPubVo.getWss())){out.print(" disabled ");}%>><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><img style="cursor:hand;position:static;" src="<%=Parameters.ROOT_PATH%>/styles/<%= styleDirectory %>/images/btn_mod.gif" onclick="selectUsers('txtUsu<%=i%>')"><%} %></td><td><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><button type="button" onclick="btnPub_click(<%=wsPubVo.getEnvId()%>, <%=wsPubVo.getWsPubId()%>,<%=i%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnPub")%>" title="<%=LabelManager.getToolTip(labelSet,"btnPub")%>"><%=LabelManager.getNameWAccess(labelSet,"btnPub")%></button><%}else if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_UNPUBLISH)){ %><button type="button" onclick="btnUnPub_click(<%=wsPubVo.getEnvId()%>, <%=wsPubVo.getWsPubId()%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnUnPub")%>" title="<%=LabelManager.getToolTip(labelSet,"btnUnPub")%>"><%=LabelManager.getNameWAccess(labelSet,"btnUnPub")%></button><%} %></td></tr><%i++;%><%}
										if(wsTreeVo.getWsTasks()!=null){
											Iterator itTsk = wsTreeVo.getWsTasks().iterator();
											while(itTsk.hasNext()){
												wsPubVo = (WsPublicationVo)itTsk.next();
												
												if(wsPubVo.getWsName()!=null && wsPubVo.getWsName() != ""){%><tr><td align="center"><img src="<%if(wsPubVo.getStatus().equals(WsPublicationVo.STATUS_PUBLISHED_NOT_OK)){
																out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority1.gif");
															}else if(wsPubVo.getStatus().equals(WsPublicationVo.STATUS_PUBLISHED_OK)){
																out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority2.gif");
															}else{
																out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority3.gif");
															}%>"></td><td style="min-width:100px"></td><td style="min-width:100px"><%=wsPubVo.getWsName()%> (<%=wsPubVo.getEnvName()%>)</td><td><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><input type="checkbox" id="chkWss<%=i%>" onclick="chkWSSClick(this,<%=i%>)" <%if("1".equals(wsPubVo.getWss())){out.print(" checked ");}%>><%}else{ %><input type="checkbox" id="chkWss<%=i%>" onclick="this.checked=<%if("1".equals(wsPubVo.getWss())){out.print("true");}else{out.print("false");}%>" <%if("1".equals(wsPubVo.getWss())){out.print(" checked ");}%>><%} %></td><td><input id="txtUsu<%=i%>" name="txtUsu<%=i%>" size="25" value="<%=wsPubVo.getWssUser()!=null?wsPubVo.getWssUser():""%>" readonly class="txtReadOnly" <%if(!"1".equals(wsPubVo.getWss())){out.print(" disabled ");}%>><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><img style="cursor:hand;position:static;" src="<%=Parameters.ROOT_PATH%>/styles/<%= styleDirectory %>/images/btn_mod.gif" onclick="selectUsers('txtUsu<%=i%>')"><%} %></td><td><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><button type="button" onclick="btnPub_click(<%=wsPubVo.getEnvId()%>, <%=wsPubVo.getWsPubId()%>,<%=i%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnPub")%>" title="<%=LabelManager.getToolTip(labelSet,"btnPub")%>"><%=LabelManager.getNameWAccess(labelSet,"btnPub")%></button><%}else if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_UNPUBLISH)){ %><button type="button" onclick="btnUnPub_click(<%=wsPubVo.getEnvId()%>, <%=wsPubVo.getWsPubId()%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnUnPub")%>" title="<%=LabelManager.getToolTip(labelSet,"btnUnPub")%>"><%=LabelManager.getNameWAccess(labelSet,"btnUnPub")%></button><%} %></td></tr><%i++;%><%}
											}
										}
									}
								}
							}%></tbody></table></div><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtBusClaWs")%></DIV><div style="height: 200px;" type="grid" id="gridList" docBean=""><table cellpadding="0" cellspacing="0"><thead class="fixedHeader"><tr><th min_width="30px" style="width:30px" title="<%=LabelManager.getToolTip(labelSet,"lblWsStatus")%>"><%=LabelManager.getName(labelSet,"lblWsStatus")%></th><th min_width="200px" style="min-width:200px;width:90%" title="<%=LabelManager.getToolTip(labelSet,"lblWsBusCla")%>"><%=LabelManager.getName(labelSet,"lblWsBusCla")%></th><th min_width="20px" style="width:20px" title="WSS">WSS</th><th min_width="180px" style="width:180px" title="User">User</th><th min_width="80px" style="min-width:80px;width:10%" title="<%=LabelManager.getToolTip(labelSet,"lblWsAct")%>"><%=LabelManager.getName(labelSet,"lblWsAct")%></th></tr></thead><tbody class="scrollContent"><%	col = dBean.getBusClassWS(uData);
							if (col != null) {
								Iterator it = col.iterator();
								WsPublicationVo wsPubVo;
								 
								while (it.hasNext()) {
									wsPubVo = (WsPublicationVo)it.next(); 
									if(wsPubVo.getWsName()!=null && wsPubVo.getWsName() != ""){%><tr><td align="center"><img src="<%if(wsPubVo.getStatus().equals(WsPublicationVo.STATUS_PUBLISHED_NOT_OK)){
													out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority1.gif");
												}else if(wsPubVo.getStatus().equals(WsPublicationVo.STATUS_PUBLISHED_OK)){
													out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority2.gif");
												}else{
													out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority3.gif");
												}%>"></td><td style="min-width:200px"><%=wsPubVo.getWsName()%> (<%=wsPubVo.getEnvName()%>)</td><td><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><input type="checkbox" id="chkWss<%=i%>" onclick="chkWSSClick(this,<%=i%>)" <%if("1".equals(wsPubVo.getWss())){out.print(" checked ");}%>><%}else{ %><input type="checkbox" id="chkWss<%=i%>" onclick="this.checked=<%if("1".equals(wsPubVo.getWss())){out.print("true");}else{out.print("false");}%>" <%if("1".equals(wsPubVo.getWss())){out.print(" checked ");}%>><%} %></td><td><input id="txtUsu<%=i%>" name="txtUsu<%=i%>" size="25" value="<%=wsPubVo.getWssUser()!=null?wsPubVo.getWssUser():""%>" readonly class="txtReadOnly" <%if(!"1".equals(wsPubVo.getWss())){out.print(" disabled ");}%>><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><img style="cursor:hand;position:static;" src="<%=Parameters.ROOT_PATH%>/styles/<%= styleDirectory %>/images/btn_mod.gif" onclick="selectUsers('txtUsu<%=i%>')"><%} %></td><td style="min-width:80px"><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><button type="button" onclick="btnPub_click(<%=wsPubVo.getEnvId()%>, <%=wsPubVo.getWsPubId()%>,<%=i%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnPub")%>" title="<%=LabelManager.getToolTip(labelSet,"btnPub")%>"><%=LabelManager.getNameWAccess(labelSet,"btnPub")%></button><%}else if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_UNPUBLISH)){ %><button type="button" onclick="btnUnPub_click(<%=wsPubVo.getEnvId()%>, <%=wsPubVo.getWsPubId()%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnUnPub")%>" title="<%=LabelManager.getToolTip(labelSet,"btnUnPub")%>"><%=LabelManager.getNameWAccess(labelSet,"btnUnPub")%></button><%} %></td></tr><%i++;%><%}	
								}
							}%></tbody></table></div><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtQryWs")%></DIV><div style="height: 200px;" type="grid" id="gridList" docBean=""><table cellpadding="0" cellspacing="0"><thead class="fixedHeader"><tr><th min_width="30px" style="width:30px" title="<%=LabelManager.getToolTip(labelSet,"lblWsStatus")%>"><%=LabelManager.getName(labelSet,"lblWsStatus")%></th><th min_width="200px" style="min-width:200px;width:90%" title="<%=LabelManager.getToolTip(labelSet,"lblWsQry")%>"><%=LabelManager.getName(labelSet,"lblWsQry")%></th><th min_width="20px" style="width:20px" title="WSS">WSS</th><th min_width="180px" style="width:180px" title="User">User</th><th min_width="80px" style="min-width:80px;width:10%" title="<%=LabelManager.getToolTip(labelSet,"lblWsAct")%>"><%=LabelManager.getName(labelSet,"lblWsAct")%></th></tr></thead><tbody class="scrollContent"><%	col = dBean.getQueryWS(uData);
							if (col != null) {
								Iterator it = col.iterator();
								WsPublicationVo wsPubVo;
								 
								while (it.hasNext()) {
									wsPubVo = (WsPublicationVo)it.next(); 
									if(wsPubVo.getWsName()!=null && wsPubVo.getWsName() != ""){%><tr><td align="center"><img src="<%if(wsPubVo.getStatus().equals(WsPublicationVo.STATUS_PUBLISHED_NOT_OK)){
													out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority1.gif");
												}else if(wsPubVo.getStatus().equals(WsPublicationVo.STATUS_PUBLISHED_OK)){
													out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority2.gif");
												}else{
													out.print(Parameters.ROOT_PATH + "/styles/" + EnvParameters.getEnvParameter(uData.getEnvironmentId(),EnvParameters.ENV_STYLE) + "/images/priority3.gif");
												}%>"></td><td style="min-width:200px"><%=wsPubVo.getWsName()%> (<%=wsPubVo.getEnvName()%>)</td><td><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><input type="checkbox" id="chkWss<%=i%>" onclick="chkWSSClick(this,<%=i%>)" <%if("1".equals(wsPubVo.getWss())){out.print(" checked ");}%>><%}else{ %><input type="checkbox" id="chkWss<%=i%>" onclick="this.checked=<%if("1".equals(wsPubVo.getWss())){out.print("true");}else{out.print("false");}%>" <%if("1".equals(wsPubVo.getWss())){out.print(" checked ");}%>><%} %></td><td><input id="txtUsu<%=i%>" name="txtUsu<%=i%>" size="25" value="<%=wsPubVo.getWssUser()!=null?wsPubVo.getWssUser():""%>" readonly class="txtReadOnly" <%if(!"1".equals(wsPubVo.getWss())){out.print(" disabled ");}%>><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><img style="cursor:hand;position:static;" src="<%=Parameters.ROOT_PATH%>/styles/<%= styleDirectory %>/images/btn_mod.gif" onclick="selectUsers('txtUsu<%=i%>')"><%} %></td><td style="min-width:80px"><%if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_PUBLISH)){%><button type="button" onclick="btnPub_click(<%=wsPubVo.getEnvId()%>, <%=wsPubVo.getWsPubId()%>,<%=i%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnPub")%>" title="<%=LabelManager.getToolTip(labelSet,"btnPub")%>"><%=LabelManager.getNameWAccess(labelSet,"btnPub")%></button><%}else if(wsPubVo.getPermitedAction().equals(WsPublicationVo.ACTION_UNPUBLISH)){ %><button type="button" onclick="btnUnPub_click(<%=wsPubVo.getEnvId()%>, <%=wsPubVo.getWsPubId()%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnUnPub")%>" title="<%=LabelManager.getToolTip(labelSet,"btnUnPub")%>"><%=LabelManager.getNameWAccess(labelSet,"btnUnPub")%></button><%} %></td></tr><%i++;%><%}	
								}
							}%></tbody></table></div><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtDelWs")%></DIV><div style="height: 200px;" type="grid" id="gridList" docBean=""><table cellpadding="0" cellspacing="0"><thead class="fixedHeader"><tr><th min_width="200px" style="min-width:200px;width:92%" title="<%=LabelManager.getToolTip(labelSet,"lblWs")%>"><%=LabelManager.getName(labelSet,"lblWs")%></th><th min_width="80px" style="min-width:80px;width:9%" title="<%=LabelManager.getToolTip(labelSet,"lblWsAct")%>"><%=LabelManager.getName(labelSet,"lblWsAct")%></th></tr></thead><tbody class="scrollContent"><%	col = dBean.getDeletedWs(uData);
							if (col != null) {
								Iterator it = col.iterator();
								 
								String wsPubVo;
								while (it.hasNext()) {
									wsPubVo = (String)it.next(); 
									if(wsPubVo!=null && wsPubVo!= ""){%><tr><td style="min-width:200px"><%=wsPubVo%></td><td style="min-width:80px"><button type="button" onclick="btnUnPubDeleted_click('<%=wsPubVo%>')" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnUnPubDeleted")%>" title="<%=LabelManager.getToolTip(labelSet,"btnUnPubDeleted")%>"><%=LabelManager.getNameWAccess(labelSet,"btnUnPubDeleted")%></button></td></tr><%i++;%><%}
								}
							}%></tbody></table></div><table class="navBar" width=100%><tr><td width=100% align="right"><button type="button" onclick="btnUnPubAll_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnUnPubAll")%>" title="<%=LabelManager.getToolTip(labelSet,"btnUnPubAll")%>"><%=LabelManager.getNameWAccess(labelSet,"btnUnPubAll")%></button></td></tr></table><br/></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD align="right"><button type="button" onclick="splash()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><script src="<%=Parameters.ROOT_PATH%>/programs/configuration/ws/ws.js"></script><%@include file="../../../components/scripts/server/endInc.jsp" %>