<%@page import="com.st.util.labels.LabelManager"%><%@page import="biz.statum.apia.web.bean.monitor.ProcessesBean"%><%@include file="../../includes/startInc.jsp" %><html><head><%@include file="../../includes/headInclude.jsp" %><link href="<system:util show="context" />/css/<system:util show="currentStyle" />/generalAdm.css" rel="stylesheet" type="text/css" /><script type="text/javascript" src="<system:util show="context" />/page/monitor/processes/task.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/navButtons.js"></script><script type="text/javascript">
		var URL_REQUEST_AJAX = '/apia.monitor.ProcessesAction.run';
		var ADDITIONAL_INFO_IN_TABLE_DATA  = false;		
		var fromEntity = '<system:edit show="value" from="theBean" field="fromEntity" />';
		var NOT_SUBPROCESS = '<system:label show="text" label="msgNotSubProcess" forScript="true" />';
		var SHOW_TSK_GANTT = '<system:edit show="constant" from="com.dogma.vo.filter.MonitorProcessFilterVo" field="SHOW_TSK_GANTT" />';
		var PRO_MAX_DUR = '<system:edit show="value" from="theBean" field="proMaxDur" />';
		var startTimeline = '<system:edit show="value" from="theBean" field="strStartTimeline" />';
	    var Timeline_ajax_url= '<system:util show="host" /><system:util show="context" />/js/timeline/simile-ajax-api.js';
        var Timeline_urlPrefix='<system:util show="host" /><system:util show="context" />/js/timeline/';       
        var Timeline_parameters='bundle=true';       
    </script><script type="text/javascript" src="<system:util show="context" />/js/timeline/timeline-api.js"></script><script type="text/javascript" src="<system:util show="context" />/page/monitor/processes/timeline.js"></script></head><body><div class="header"></div><div class="body" id="bodyDiv"><div class="optionsContainer" id="optionsContainer"><div class="fncPanel info"><div class="title"><span><system:label show="tooltip" label="sbtMonTsk" />: <system:edit show="value" from="theBean" field="vo.proTitle"/> (<system:edit show="value" from="theBean" field="vo.processIdentification"/>)</span><span class="panelPinShow" id="panelPinShow">&nbsp;</span><span class="panelPinHidde" id="panelPinHidde">&nbsp;</span></div><div class="content divFncDescription"><div class="fncDescriptionImage" src="<system:edit show="value" from="theBean" field="fncImage"/>"></div><div id="fncDescriptionText"><system:label show="text" label="dscFncProcMon"/></div><div class="clear"></div></div></div><div class="fncPanel buttons"><div class="title"><system:label show="text" label="titActions"/></div><div class="content"><div id="btnExport" class="button"><system:label show="text" label="btnExport" /></div><div id="btnBackToList" class="button" title="<system:label show="tooltip" label="btnVol" />"><system:label show="text" label="btnVol" /></div><div id="btnBack" class="button" title="<system:label show="tooltip" label="btnAnt" />"><system:label show="text" label="btnAnt" /></div></div></div><%@include file="show_combo.jsp" %></div><div class="gridContainer" id="gridContainer"><div class="gridBody" id="gridBody"><table cellpadding="0" cellspacing="0" id="flashTable"><tr><td><div id="timeLineDiv" style="height: 300px; border: 1px solid #aaa"></div></td></tr></table></div><!-- MESSAGES --><div class="message hidden" id="messageContainer"></div></div></div><%@include file="../../includes/footer.jsp" %></body></html>
