<%@page import="com.st.util.labels.LabelManager"%><%@page import="biz.statum.apia.web.bean.monitor.ProcessesBean"%><%@include file="../../includes/startInc.jsp" %><html lang="<%=biz.statum.apia.web.bean.BasicBeanStatic.getUserDataStatic(request).getLangCode()%>"><head><%@include file="../../includes/headInclude.jsp" %><script type="text/javascript" src="<system:util show="context" />/js/go-debug.js"></script><script type="text/javascript" src="<system:util show="context"/>/page/monitor/processes/visualElements.js"></script><script type="text/javascript" src="<system:util show="context" />/page/monitor/processes/task.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/navButtons.js"></script><script type="text/javascript">
		var URL_REQUEST_AJAX = '/apia.monitor.ProcessesAction.run';
		var ADDITIONAL_INFO_IN_TABLE_DATA  = false;		
		var fromEntity = '<system:edit show="value" from="theBean" field="fromEntity" />';
		var NOT_SUBPROCESS = '<system:label show="text" label="msgNotSubProcess" forScript="true" />';
		var SHOW_TSK_GANTT = '<system:edit show="constant" from="com.dogma.vo.filter.MonitorProcessFilterVo" field="SHOW_TSK_GANTT" />';
		var PRO_MAX_DUR = '<system:edit show="value" from="theBean" field="proMaxDur" />';
		var VUSUAL_ELEMENTS = true;
		
		// Labels
		var TASK_STATE = '<system:label show="text" label="lblMonProEleInstSta" forScript="true" />';
		var POOLS_USR = '<system:label show="text" label="lblMonPoolNom" forScript="true" />';
		var USR = '<system:label show="text" label="lblUsu" forScript="true" />';
		var QUAL_DTE = '<system:label show="text" label="lblMonProEleInstDatRea" forScript="true" />';
		var END_DTE = '<system:label show="text" label="lblMonProEleInstDatEnd" forScript="true" />';		
	</script></head><body><div class="body" id="bodyDiv"><div class="optionsContainer" id="optionsContainer"><div class="fncPanel info"><div class="title"><span><system:label show="text" label="sbtMonTsk" />: <system:edit show="value" from="theBean" field="vo.proTitle"/> (<system:edit show="value" from="theBean" field="vo.processIdentification"/>)</span><span class="panelPinShow" id="panelPinShow">&nbsp;</span><span class="panelPinHidde" id="panelPinHidde">&nbsp;</span></div><div class="content divFncDescription"><div class="fncDescriptionImage" data-src="<system:edit show="value" from="theBean" field="fncImage"/>"></div><div id="fncDescriptionText"><system:label show="text" label="dscFncProcMon"/></div><div class="clear"></div></div></div><div class="fncPanel options"></div><div class="fncPanel buttons"><div class="title"><system:label show="text" label="titActions"/></div><div class="content"><system:edit show="ifValue" from="theBean" field="visMonOrder" value="true"><div id="btnReOrganize" class="button"><system:label show="text" label="btnReOrd" /></div></system:edit><system:edit show="ifValue" from="theBean" field="visMonOrder" value="false"><div id="btnOrganize" class="button"><system:label show="text" label="btnOrd" /></div></system:edit><div id="btnBackToList" class="button" title="<system:label show="tooltip" label="btnVol" />"><system:label show="text" label="btnVol" /></div><div id="btnBack" class="button" title="<system:label show="tooltip" label="btnAnt" />"><system:label show="text" label="btnAnt" /></div></div></div><%@include file="show_combo.jsp" %></div><div class="gridContainer" id="gridContainer"><div class="gridBody" id="gridBody" style="height:550px;"><div style="display: none"><p id="myJson"><system:edit show="value" from="theBean" field="json"/></p></div><div id="htmlInfo" class="htmlInfo" style="display: none"></div><div id="jsonTable" class="jsonTable"></div></div><!-- MESSAGES --><div class="message hidden" id="messageContainer"></div></div></div><%@include file="../../includes/footer.jsp" %></body></html>
