var addPool;

function initPage(){
	//crear spinner de espere un momento
	sp = new Spinner(document.body,{message:WAIT_A_SECOND});
	
	initAdminFieldOnChangeHighlight();
	initAdminActionsEdition();
	initAdminFav();
	
	getBodyController().canRemoveTab = function() { return ! AT_LEAST_ON_FIELD_INPUT_CHANGED; };
	
	addPool = $('addPool');
	
	addPool.addEvent("click", function(e) {
		e.stop();
		//setear variables de configuracion del modal de grupos
		POOLMODAL_SHOWAUTOGENERATED = false;
		POOLMODAL_SHOWNOTAUTOGENERATED = true;
		POOLMODAL_SHOWGLOBAL = true;
		POOLMODAL_SELECTONLYONE = true;
		POOLMODAL_FROMENVS = currentEnvId;
		POOLMODAL_ONLY_IN_HIERARCHY = true;
		FETCH_ALL_IN_HIERARCHY = true;
		
		//abrir modal
		showPoolsModal(processPoolsModalReturn);
	});
	
	$('poolsContainter').onRemove = function() {
		addPool.inject($('poolsContainter'));
	};
	
	if(POOL_ID) {
		addActionElement($('poolsContainter'), POOL_NAME, POOL_ID, "poolId");
		addPool.dispose();
	}
	initAdminModalHandlerOnChangeHighlight($('poolsContainter'));
	
	
	$('addUser').addEvent("click", function(e) {
		e.stop();
		//setear variables de configuracion del modal de usuarios
		USERMODAL_GLOBAL_AND_ENV = true;
		
		//abrir modal
		showUsersModal(processUsersModalReturn);
	});
	
	if(ADMINS && ADMINS.length) {
		for(var i = 0; i < ADMINS.length; i++) {
			addActionElement($('usersContainter'), ADMINS[i], ADMINS[i], "usrId");
		}
	}
	initAdminModalHandlerOnChangeHighlight($('usersContainter'));
	
	initPoolMdlPage();
	initUsrMdlPage();
}

function processPoolsModalReturn(ret) {
	if(ret && ret.length) {
		addActionElement($('poolsContainter'), ret[0].getRowContent()[0], ret[0].getRowId(), "poolId");
		addPool.dispose();
	}
}

function processUsersModalReturn(ret) {
	ret.each(function(e) {
		var login = e.getRowContent()[0];
		addActionElement($('usersContainter'), login, login, "usrId");
	});
}