function initPage(){
	//crear spinner de espere un momento
	sp = new Spinner(document.body,{message:WAIT_A_SECOND});
	
	Generic.updateFncImages();
	
	$('frmData').formChecker = new FormCheck('frmData', {
		submit:false,
		display : {
			keepFocusOnError : 1,
			tipsPosition: 'left',
			tipsOffsetX: -10
		}
	});
	
	var btnSend = $('btnSend');
	var addUser = $('addUser');
	var addPool = $('addPool');
	var usersContainter = $('usersContainter');
	var poolsContainter = $('poolsContainter');
	
	if (btnSend) {
		btnSend.addEvent('click', function(e) {
			e.stop();
			
			var form = $('frmData');
			if(!form.formChecker.isFormValid()){
				return;
			}
			
			var params = getFormParametersToSend(form);
			
			var request = new Request({
				method: 'post',
				url: CONTEXT + URL_REQUEST_AJAX + '?action=send&isAjax=true' + TAB_ID_REQUEST,
				onRequest: function() { SYS_PANELS.showLoading(); },
				onComplete: function(resText, resXml) { modalProcessXml(resXml); clearFields(); }
			}).send(params);
		});
	}
	
	if (addUser) {
		addUser.addEvent("click", function(e) {
			e.stop();
			//setear variables de configuracion del modal de grupos
			showUsersModal(processUsersModalReturn);
		});
	}
	
	if (addPool) {
		addPool.addEvent("click", function(e) {
			e.stop();
			//setear variables de configuracion del modal de grupos
			POOLMODAL_SHOWAUTOGENERATED = false;
			POOLMODAL_SHOWGLOBAL = true;
			showPoolsModal(processPoolsModalReturn);
		});
	}
	
	if (usersContainter) {
		usersContainter.onRemove=function(objId){
			var arr = getActionElementsIds(usersContainter);
			if(arr.length==0){
				$('allUsersOption').setStyle("display",'');
			}	
		}
	}
	
	if (poolsContainter) {
		poolsContainter.onRemove=function(objId){
			var arr = getActionElementsIds(poolsContainter);
			if(arr.length==0){
				$('allPoolsOption').setStyle("display",'');
			}	
		}
	}
	
	initAdminFav();
	initUsrMdlPage();
	initPoolMdlPage();
}

function processPoolsModalReturn(ret){
	ret.each(function(e){
		var text = e.getRowContent()[0];
		addActionElement($('poolsContainter'),text,text,"poolName");
	});
	
	if (ret && ret.length > 0) {
		$('allPoolsOption').setStyle("display",'none');
		$('sendAllPools').checked = false;
	}
}

function clearFields() {
	var usersContainter = $('usersContainter');
	var poolsContainter = $('poolsContainter');
	
//	getActionElementsIds(poolsContainter).each(function(ele) { ele.dispose(); });
//	getActionElementsIds(poolsContainter).each(function(ele) { ele.dispose(); });
	getActionElements(poolsContainter).each(function(ele) { ele.dispose(); });
	getActionElements(poolsContainter).each(function(ele) { ele.dispose(); });
	
	$('allUsersOption').setStyle("display",'');
	$('allPoolsOption').setStyle("display",'');
	
	$('sendAllUsers').checked = false;
	$('sendAllPools').checked = false;
	
	$('blockMsg').checked = false;
	$('msg').value = '';
}

function processUsersModalReturn(ret){
	ret.each(function(e){
		var text = e.getRowContent()[0];
		addActionElement($('usersContainter'),text,text,"usrLogin");
	});
	
	if (ret && ret.length > 0) {
		$('allUsersOption').setStyle("display",'none');
		$('sendAllUsers').checked = false;
	}
}