<%@page import="com.dogma.vo.*"%><%@page import="com.dogma.vo.custom.*"%><%@page import="com.dogma.business.*"%><%@page import="com.dogma.bean.scheduler.SchedulerBean"%><%@page import="com.dogma.dao.DataBaseDAO"%><%@page import="java.util.*"%><%@page import="com.dogma.util.DogmaUtil"%><%@page import="com.dogma.util.DogmaUtil"%><%@page import="com.dogma.business.querys.factory.*" %><% if (QueryVo.TYPE_QUERY.equals(queryVo.getQryType())) { %><div type="tab" style="visibility:hidden" tabTitle="<%=LabelManager.getToolTip(labelSet,"tabQryAct")%>" tabText="<%=LabelManager.getName(labelSet,"tabQryAct")%>"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtQryAct")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td><input type="checkbox" value="1" onclick="chkActVieQry_click()" name="chkActVieQry" id="chkActVieQry" <%= queryVo.getAction(QueryVo.ACTION_VIEW_QUERY)?"checked":"" %>></td><td><%=LabelManager.getName(labelSet,"lblQryActVieQry")%></td><td></td><td></td></tr></table><div type="grid" id="gridActionQuery" style="height:200px"><table id="tblActionQuery" width="300px" cellpadding="0" cellspacing="0"><thead><tr><th style="width:0px;display:none;" title=">"></th><th min_width="200px" style="min-width:200px;width:100%" title="<%=LabelManager.getToolTip(labelSet,"lblNom")%>"><%=LabelManager.getName(labelSet,"lblNom")%></th><th min_width="150px" style="width:150px" title="<%=LabelManager.getToolTip(labelSet,"lblQryAllowUsrSelectAutoFilter")%>"><%=LabelManager.getName(labelSet,"lblQryAllowUsrSelectAutoFilter")%></th></tr></thead><tbody id="tblActionQueryBody"><%
												Collection col = queryVo.getActionsTo();
												if (col != null && col.size() > 0) {
													for (Iterator it = col.iterator(); it.hasNext(); ) {
														QryNavigationVo navVo = (QryNavigationVo) it.next(); %><tr><td style="width:0px;display:none;"><input type="hidden" name="chkactVieQryTo"><input type="hidden" name="actVieQryTo" value="<%= navVo.getQryToId() %>"><input type="hidden" name="actVieQryToName" value="<%= navVo.getQryToName() %>"></td><td style="min-width:200px"><%= dBean.fmtHTML(navVo.getQryToName()) %></td><td><input type="checkbox" name="actVieQryToAllowAutoFilter" id="actVieQryToAllowAutoFilter" value="1" <%= navVo.getFlagValue(QryNavigationVo.FLAG_ALLOW_USER_SELECT_AUTO_FILTER) ? "checked" : "" %>></td></tr><%
													} 
												} %></tbody></table></div><table class="navBar"><tr><td align="left"><button type="button" id="upActionQuery" onclick="upActionQuery_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnUp")%>" title="<%=LabelManager.getToolTip(labelSet,"btnUp")%>"><%=LabelManager.getNameWAccess(labelSet,"btnUp")%></button><button type="button" id="downActionQuery" onclick="downActionQuery_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnDown")%>" title="<%=LabelManager.getToolTip(labelSet,"btnDown")%>"><%=LabelManager.getNameWAccess(labelSet,"btnDown")%></button></td><td>&nbsp;</td><td align="right"><button type="button" id="btnAddActionQuery" onclick="btnAddActionQuery_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnAgr")%>" title="<%=LabelManager.getToolTip(labelSet,"btnAgr")%>"><%=LabelManager.getNameWAccess(labelSet,"btnAgr")%></button><button type="button" id="btnDelActionQuery" onclick="btnDelActionQuery_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnEli")%>" title="<%=LabelManager.getToolTip(labelSet,"btnEli")%>"><%=LabelManager.getNameWAccess(labelSet,"btnEli")%></button></td></tr></table><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><% /* %><tr><td><input type="checkbox" value="1" onclick="chkActVieFor_click()" name="chkActVieFor" id="chkActVieFor" <%= queryVo.getAction(QueryVo.ACTION_VIEW_FORM)?"checked":"" %>></td><td><%=LabelManager.getName(labelSet,"lblQryActVieFor")%></td><td><%=LabelManager.getName(labelSet,"lblSelQry")%>:</td><td><select name="actVieForTo" id="actVieForTo" <%= (!queryVo.getAction(QueryVo.ACTION_VIEW_FORM))?"disabled":"" %>><%
								if (dBean.getQueryForms() != null) {
									QryNavigationVo navVo = queryVo.getNavigationVo(QueryVo.ACTION_VIEW_FORM);
									Iterator iterator = dBean.getQueryForms().iterator();
									while (iterator.hasNext()) {
										QueryVo qVo = (QueryVo) iterator.next(); %><option value="<%=dBean.fmtInt(qVo.getQryId())%>" <%= (navVo != null && navVo.getQryToId().equals(qVo.getQryId()))?"selected":"" %>><%=dBean.fmtHTML(qVo.getQryName())%></option><%
									}
								} %></select></td></tr><% */ %><%if(queryVo.getDbConId()!=null && queryVo.getDbConId().equals(new Integer(-1))){ %><tr><td><input type="checkbox" value="1" name="chkActVieEnt" id="chkActVieEnt" <%= queryVo.getAction(QueryVo.ACTION_VIEW_ENTITY)?"checked":"" %>></td><td colspan="3"><%=LabelManager.getName(labelSet,"lblQryActVieEnt")%> (<%= QueryColumns.getInstance().getRequiereActionColumns(QueryVo.ACTION_VIEW_ENTITY) %>)</td></tr><tr><td><input type="checkbox" value="1" name="chkActViePro" id="chkActViePro" <%= queryVo.getAction(QueryVo.ACTION_VIEW_PROCESS)?"checked":"" %>></td><td colspan="3"><%=LabelManager.getName(labelSet,"lblQryActViePro")%> (<%= QueryColumns.getInstance().getRequiereActionColumns(QueryVo.ACTION_VIEW_PROCESS) %>)</td></tr><tr><td><input type="checkbox" value="1" name="chkActViwTas" id="chkActViwTas" <%= queryVo.getAction(QueryVo.ACTION_VIEW_TASK)?"checked":"" %>></td><td colspan="3"><%=LabelManager.getName(labelSet,"lblQryActVieTas")%> (<%= QueryColumns.getInstance().getRequiereActionColumns(QueryVo.ACTION_VIEW_TASK) %>)</td></tr><tr><td><input type="checkbox" value="1" name="chkActWorEnt" id="chkActWorEnt" <%= queryVo.getAction(QueryVo.ACTION_WORK_ENTITY)?"checked":"" %>></td><td colspan="3"><%=LabelManager.getName(labelSet,"lblQryActWorEnt")%> (<%= QueryColumns.getInstance().getRequiereActionColumns(QueryVo.ACTION_WORK_ENTITY) %>)</td></tr><tr><td><input type="checkbox" value="1" name="chkActWorTas" id="chkActWorTas" <%= queryVo.getAction(QueryVo.ACTION_WORK_TASK)?"checked":"" %>></td><td colspan="3"><%=LabelManager.getName(labelSet,"lblQryActWorTas")%> (<%= QueryColumns.getInstance().getRequiereActionColumns(QueryVo.ACTION_WORK_TASK) %>)</td></tr><tr><td><input type="checkbox" value="1" name="chkActAcqTas" id="chkActAcqTas" <%= queryVo.getAction(QueryVo.ACTION_ACQUIRE_TASK)?"checked":"" %>></td><td colspan="3"><%=LabelManager.getName(labelSet,"lblQryActAcqTas")%> (<%= QueryColumns.getInstance().getRequiereActionColumns(QueryVo.ACTION_ACQUIRE_TASK) %>)</td></tr><tr><td><input type="checkbox" value="1" name="chkActComTas" id="chkActComTas" <%= queryVo.getAction(QueryVo.ACTION_COMPLETE_TASK)?"checked":"" %>></td><td colspan="3"><%=LabelManager.getName(labelSet,"lblQryActComTas")%> (<%= QueryColumns.getInstance().getRequiereActionColumns(QueryVo.ACTION_COMPLETE_TASK) %>)</td></tr><% } %></table></div><% } %>

