<%@page import="com.dogma.vo.*"%><%@page import="com.dogma.vo.custom.*"%><%@page import="com.dogma.business.*"%><%@page import="com.dogma.bean.scheduler.SchedulerBean"%><%@page import="com.dogma.dao.DataBaseDAO"%><%@page import="java.util.*"%><%@page import="com.dogma.util.DogmaUtil"%><%@page import="com.dogma.util.DogmaUtil"%><%@page import="com.dogma.business.querys.factory.*" %><% if (QueryVo.TYPE_MON_ENTITY.equals(queryVo.getQryType())) { %><div type="tab" tabTitle="<%=LabelManager.getToolTip(labelSet,"tabQryAttRemap")%>" tabText="<%=LabelManager.getName(labelSet,"tabQryAttRemap")%>"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtQryAttRemp")%></DIV><div type="grid" id="gridRemap" style="height:200px"><table width="500px" cellpadding="0" cellspacing="0"><thead><tr><th style="width:0px;display:none;" title="<%=LabelManager.getToolTip(labelSet,"lblSel")%>"></th><th min_width="200px" style="width:200px" title="<%=LabelManager.getToolTip(labelSet,"lblAtt")%>"><%=LabelManager.getName(labelSet,"lblAtt")%></th><th min_width="200px" style="min-width:200px;width:100%" title="<%=LabelManager.getToolTip(labelSet,"lblBusEnt")%>"><%=LabelManager.getName(labelSet,"lblBusEnt")%></th></tr></thead><tbody class="scrollContent"><%
						   			if (queryVo.getRemapingColumns() != null){
										Iterator itShow = queryVo.getRemapingColumns().iterator();
										int count = 0;
										while (itShow.hasNext()) {
											QryColumnVo columnVo = (QryColumnVo) itShow.next(); %><tr><td style="width:0px;display:none;"><input type="hidden" name="checkRemapSel"><input type="hidden" name="hidRempColId" value="true"><input type=hidden name="hidRempAttId" value="<%=dBean.fmtInt(columnVo.getAttId())%>"><input type=hidden name="hidRempAttName" value="<%=dBean.fmtStr(columnVo.getQryColName())%>"><input type=hidden name="hidRempAttType" value="<%=dBean.fmtStr(columnVo.getQryColDataType())%>"></td><td><%=dBean.fmtStr(columnVo.getQryColName())%></td><td style="min-width:200px"><select name="cmbRemapBusEntIdShow" p_required="true"><option value=""></option><% if (dBean.getBusEntities() != null) {
								   						for (Iterator it = dBean.getBusEntities().iterator(); it.hasNext(); ) {
								   							BusEntityVo busEntVo = (BusEntityVo) it.next(); %><option value="<%= busEntVo.getBusEntId() %>" <% if (busEntVo.getBusEntId().equals(columnVo.getBusEntId())) { %>selected<% } %>><%= busEntVo.getBusEntName() %></option><%
								   						}
								   					} %></select></td></tr><% }
									} %></tbody></table></div><table class="navBar"><tr><td></td><td align="right"><button type="button" onclick="btnAddRemapAtt_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnAgrAtt")%>" title="<%=LabelManager.getToolTip(labelSet,"btnAgrAtt")%>"><%=LabelManager.getNameWAccess(labelSet,"btnAgrAtt")%></button><button type="button" onclick="btnDelRemap_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnEli")%>" title="<%=LabelManager.getToolTip(labelSet,"btnEli")%>"><%=LabelManager.getNameWAccess(labelSet,"btnEli")%></button></td></tr></table></div><% } %>

