<%@page import="com.dogma.bean.GenericBean"%><%@page import="com.dogma.Parameters"%><jsp:useBean id="gBean" scope="session" class="com.dogma.bean.GenericBean"></jsp:useBean><%
response.setCharacterEncoding(Parameters.APP_ENCODING);
response.setContentType("text/xml");
String xml = "";
boolean showGlobal = "true".equals(request.getParameter("showGlobal"));
boolean showAutogenerated = "true".equals(request.getParameter("showAutogenerated"));
boolean showOnlyEnv = "true".equals(request.getParameter("showOnlyEnv"));
boolean envAndGlobal = "true".equals(request.getParameter("envAndGlobal"));

String desc = null;
if(request.getParameter("desc")!=null && request.getParameter("desc").length() >0){
	desc = request.getParameter("desc");
}

if(envAndGlobal){ 
	xml = gBean.getPoolsGlobalAndEnvXML(request.getParameter("name"),new Integer(request.getParameter("envId")),showGlobal,showAutogenerated,"true".equals(request.getParameter("exactMatch")),desc);
} else {
	if (showOnlyEnv) {
		xml = gBean.getPoolsEnvXML(request.getParameter("name"),new Integer(request.getParameter("envId")),showGlobal,showAutogenerated,"true".equals(request.getParameter("exactMatch")),desc);
	} else {
		xml = gBean.getPoolsXML(request.getParameter("name"),request.getParameter("showSameAs"),showGlobal,showAutogenerated,"true".equals(request.getParameter("exactMatch")),desc);
	}
}
out.clear();
out.print(xml);
%>