<%@page import="com.dogma.vo.*"%><%@page import="java.util.*"%><%@page import="com.dogma.bean.query.MonitorProcessesBean"%><%@include file="../../../../components/scripts/server/startInc.jsp" %><HTML><head><%@include file="../../../../components/scripts/server/headInclude.jsp" %></head><body><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.query.MonitorTasksBean"></jsp:useBean><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><% System.out.println(2131231);  %><TD><%=LabelManager.getName(labelSet,"titMonTsk")%>: <%= dBean.getMonTaskVo().getTskTitle() %> (<%= dBean.getMonTaskVo().getProTitle() + " - " + dBean.getMonTaskVo().getProInstIdentification() %>)</TD><TD></TD></TR></TABLE><DIV id="divContent" class="divContent"><form id="frmMain" name="frmMain" method="POST"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtMonTsk")%></DIV><div type="grid" id="gridList" style="height:<%=Parameters.SCREEN_LIST_SIZE%>px"><table width="500px" cellpadding="0" cellspacing="0"><thead><tr><th style="width:200px" title="<%=LabelManager.getToolTip(labelSet,"lblTskTit")%>"><%=LabelManager.getName(labelSet,"lblTskTit")%></th><th style="width:100px" title="<%=LabelManager.getToolTip(labelSet,"lblMonPoolNom")%>"><%=LabelManager.getName(labelSet,"lblMonPoolNom")%></th><th style="width:100px" title="<%=LabelManager.getToolTip(labelSet,"lblMonProEleInstSta")%>"><%=LabelManager.getName(labelSet,"lblMonProEleInstSta")%></th><th style="width:150px" title="<%=LabelManager.getToolTip(labelSet,"lblMonProEleInstDatRea")%>"><%=LabelManager.getName(labelSet,"lblMonProEleInstDatRea")%></th><th style="width:150px" title="<%=LabelManager.getToolTip(labelSet,"lblMonProEleInstDatEnd")%>"><%=LabelManager.getName(labelSet,"lblMonProEleInstDatEnd")%></th><th style="width:100px" title="<%=LabelManager.getToolTip(labelSet,"lblMonProEleInstHtyEve")%>"><%=LabelManager.getName(labelSet,"lblMonProEleInstHtyEve")%></th><th style="width:150px" title="<%=LabelManager.getToolTip(labelSet,"lblMonProEleInstHtyDay")%>"><%=LabelManager.getName(labelSet,"lblMonProEleInstHtyDay")%></th></tr></thead><tbody><%
				   			Collection col = dBean.getTskDetails();
							if (col != null) {
								Iterator it = col.iterator();
								int i = 0;
								MonitorTaskVo mPITVo;
								Integer oldProEleInstId = null;
								while (it.hasNext()) {
									mPITVo = (MonitorTaskVo) it.next(); %><tr <%if (i % 2 == 0) {%>class="trOdd"<%}%> row_id="<%=dBean.fmtStr(mPITVo.getReqString())%>" id=LIST><td <%=mPITVo.isLate()?"class=\"tdProLat\"":mPITVo.isInAlert()?"class=\"tdProInAle\"":""%>><%=dBean.fmtHTML(mPITVo.getTskTitle())%></td><td <%=mPITVo.isLate()?"class=\"tdProLat\"":mPITVo.isInAlert()?"class=\"tdProInAle\"":""%>><%=dBean.fmtHTML(mPITVo.getPoolName())%></td><td <%=mPITVo.isLate()?"class=\"tdProLat\"":mPITVo.isInAlert()?"class=\"tdProInAle\"":""%>><%=
											ProEleInstanceVo.ELE_STATUS_WAITING.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaWai"):
											ProEleInstanceVo.ELE_STATUS_READY.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaRea"):
											ProEleInstHistoryVo.HTY_EVENT_RELEASE.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaRea"):
											ProEleInstanceVo.ELE_STATUS_ACQUIRED.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaAcq"):
											ProEleInstanceVo.ELE_STATUS_COMPLETED.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaCom"):
											ProEleInstanceVo.ELE_STATUS_UNDO.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaCom"):
											ProEleInstanceVo.ELE_STATUS_CANCELLED.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaCan"):
											ProEleInstanceVo.ELE_STATUS_SKIPPED.equals(mPITVo.getProEleInstStatus())?LabelManager.getName(labelSet,"lblMonProEleInstStaSki"):""
										%></td><td <%=mPITVo.isLate()?"class=\"tdProLat\"":mPITVo.isInAlert()?"class=\"tdProInAle\"":""%>><%=dBean.fmtHTMLAMPM(mPITVo.getProEleInstDateReady())%></td><td <%=mPITVo.isLate()?"class=\"tdProLat\"":mPITVo.isInAlert()?"class=\"tdProInAle\"":""%>><%=dBean.fmtHTMLAMPM(mPITVo.getProEleInstDateEnd())%></td><td <%=mPITVo.isLate()?"class=\"tdProLat\"":mPITVo.isInAlert()?"class=\"tdProInAle\"":""%>><%=
											ProEleInstHistoryVo.HTY_EVENT_CREATED.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveCre"):
											ProEleInstHistoryVo.HTY_EVENT_WAITING.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveWai"):
											ProEleInstHistoryVo.HTY_EVENT_READY.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveRea"):
											ProEleInstHistoryVo.HTY_EVENT_ACQUIRED.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveAcq"):
											ProEleInstHistoryVo.HTY_EVENT_COMPLETED.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveCom"):
											ProEleInstHistoryVo.HTY_EVENT_UNDO.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveCom"):
											ProEleInstHistoryVo.HTY_EVENT_CANCELLED.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveCan"):
											ProEleInstHistoryVo.HTY_EVENT_RELEASE.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveRel"):
											ProEleInstHistoryVo.HTY_EVENT_SKIPPED.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveSki"):
											ProEleInstHistoryVo.HTY_EVENT_REASIGNED.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveReg"):
											ProEleInstHistoryVo.HTY_EVENT_ELEVATED.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveEle"):
											ProEleInstHistoryVo.HTY_EVENT_DELEGATED.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveDel"):
											ProEleInstHistoryVo.HTY_EVENT_DEALLOCATE.equals(mPITVo.getHtyEvent())?LabelManager.getName(labelSet,"lblMonProEleInstHtyEveDea"):""
										%></td><td <%=mPITVo.isLate()?"class=\"tdProLat\"":mPITVo.isInAlert()?"class=\"tdProInAle\"":""%>><%=dBean.fmtHTMLAMPM(mPITVo.getHtyDate())%></td></tr><%
									i++;
								}
							}%></tbody></table><IFRAME name="idResult" id="idResult" height="0" width="0" frameborder="0"></IFRAME></div><table class="navBar"><COL class="col1"><COL class="col2"><tr><td></td><td align="right"><button type="button" onclick="btnTskExport_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnExport")%>" title="<%=LabelManager.getToolTip(labelSet,"btnExport")%>"><%=LabelManager.getNameWAccess(labelSet,"btnExport")%></button><button type="button" onclick="btnDetTsk_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnMonDet")%>" title="<%=LabelManager.getToolTip(labelSet,"btnMonDet")%>"><%=LabelManager.getNameWAccess(labelSet,"btnMonDet")%></button><button type="button" onclick="btnBack_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnVol")%>" title="<%=LabelManager.getToolTip(labelSet,"btnVol")%>"><%=LabelManager.getNameWAccess(labelSet,"btnVol")%></button></td></tr></table></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD><button type="button" onclick="splash()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><%@include file="../../../../components/scripts/server/endInc.jsp" %><script language="javascript" src='<%=Parameters.ROOT_PATH%>/programs/query/monitor/task/monitor.js'></script><script language="javascript">

var fromQueryTaskMonitor = <%= dBean.isFromQueryTaskMonitor() %></script>
