<%@page import="com.dogma.vo.*"%><%@include file="../../../../components/scripts/server/startInc.jsp" %><%@page import="com.dogma.util.DogmaUtil"%><%@page import="com.dogma.bean.query.TaskSchedulerMonitorBean"%><HTML><head><%@include file="../../../../components/scripts/server/headInclude.jsp" %><script language='javascript' src='<%=Parameters.ROOT_PATH%>/programs/query/monitor/taskScheduler/taskSchQuery.js'></script><script language='javascript' src='<%=Parameters.ROOT_PATH%>/scripts/apiaFunctions.js'></script></head><body"><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.query.TaskSchedulerMonitorBean"></jsp:useBean><%
TaskSchedulerVo tskSchVo = dBean.getTaskSchedulerVo();
TskSchNumberVo tskSchNumberVo = dBean.getTskSchNumberVo();
String strMonday = dBean.getMonday(tskSchNumberVo.getTskSchNumDte());
String actualMonday = dBean.getMonday(new Date());

%><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,"titTskScheduler")%></TD><TD></TD></TR></TABLE><div id="divContent"><form id="frmMain" name="frmMain" method="POST"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtDatTskSch")%></DIV><!-- GRILLA CON LA AGENDA --><%=dBean.buildScheduler(request, strMonday, actualMonday)%></FORM></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD><button type="button" onclick="btnConf()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnCon")%>" title="<%=LabelManager.getToolTip(labelSet,"btnCon")%>"><%=LabelManager.getNameWAccess(labelSet,"btnCon")%></button><button type="button" onclick="btnBack_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnVol")%>" title="<%=LabelManager.getToolTip(labelSet,"btnVol")%>"><%=LabelManager.getNameWAccess(labelSet,"btnVol")%></button><button type="button" onclick="btnExit_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><%@include file="../../../../components/scripts/server/endInc.jsp" %>


