function checkPeriodicity() {
	var cmbPeri = document.getElementById("cmbPeri");
	var cmbSchAfterSchId = document.getElementById("cmbSchAfterSchId");
	
	if (cmbPeri.selectedIndex != -1 && cmbPeri.options[cmbPeri.selectedIndex].value == perAfterSch) {
		cmbSchAfterSchId.disabled = false;
		setRequiredField(cmbSchAfterSchId);
	} else {
		cmbSchAfterSchId.disabled = true;
		unsetRequiredField(cmbSchAfterSchId);
	}
}

function btnAddPool_click(gridName, notType) {
	var rets = openModal("/programs/modals/pools.jsp?showAutogenerated=true&showGlobal=true&showOnlyEnv=true&envId="+envId,500,350);
	var doLoad=function(rets){
		if (rets != null) {
			if (rets != null) {
				for (j = 0; j < rets.length; j++) {
					var ret = rets[j];
					var addRet = true;
					trows=document.getElementById(gridName).rows;
					for (i=0;i<trows.length && addRet;i++) {
						if (trows[i].getElementsByTagName("TD")[0].getElementsByTagName("INPUT")[1].value == ret[0]) {
							addRet = false;
						}
					}
					
					if (addRet) {
						var oTd0 = document.createElement("TD"); 
						var oTd1 = document.createElement("TD"); 
						var oTd2 = document.createElement("TD"); 
						
						oTd0.innerHTML = "<input type='checkbox' name='chkPoolSel'><input type='hidden' name='chkPool'><input type=hidden name='poolName'><input type=hidden name='poolDesc'><input type=hidden name='poolNotType'>";
						
						oTd0.getElementsByTagName("INPUT")[1].value = ret[0];
						oTd0.getElementsByTagName("INPUT")[2].value = ret[1];
						oTd0.getElementsByTagName("INPUT")[3].value = ret[4];
						oTd0.getElementsByTagName("INPUT")[4].value = notType;
						oTd0.align="center";
						
						if(ret[2]==1){
							oTd1.innerHTML = "<B>"+ret[1]+"</B>";			
						} else {
							oTd1.innerHTML = ret[1];			
						}
						
						oTd2.innerHTML = ret[4];		
						var oTr = document.createElement("TR");
						oTr.appendChild(oTd0);
						oTr.appendChild(oTd1);
						oTr.appendChild(oTd2);
						document.getElementById(gridName).addRow(oTr);
					}
				}
			}
		}
	}
	rets.onclose=function(){
		doLoad(rets.returnValue);
	}
}

function btnDelPool_click(gridName) {
	document.getElementById(gridName).removeSelected();
}

function getDateFromString(date, hours) {
	var month;
	var day;
	var year;
	var date_split = date.split(GNR_DATE_SEPARATOR);
	if ('M' == strDateFormat.charAt(0)) {
		month = date_split[0];
		day = date_split[1];
		year = date_split[2];
	} else if ('d' == strDateFormat.charAt(0)) {
		day = date_split[0];
		month = date_split[1];
		year = date_split[2];
	} else if ('y' == strDateFormat.charAt(0)) {
		year = date_split[0];
		month = date_split[1];
		day = date_split[2];
	}
	
	var d = new Date(year, month - 1, day);	
	
	if(hours) {
		//Edicion de scheduler no usa formato de hora definido en parametros del ambiente
		var hours_split = hours.split(GNR_TIME_SEPARATOR);		
		d.setHours(hours_split[0]);
		d.setMinutes(hours_split[1]);
	}
	
	return d;
}

function btnConf_click(){
	if (verifyRequiredObjects()) {
		if (checkNodeName()){
			if(checkHour(document.getElementById("txtHorIni"))){
				if (document.getElementById("txtFchFin").value != null && document.getElementById("txtFchFin").value.indexOf('_') < 0){
				
					if (document.getElementById("txtHorFin").value == "__:__"){
						document.getElementById("txtHorFin").value = "00:00";
					}	
					
					//if (document.getElementById("txtHorFin").value != "__:__"){
						if (checkHour(document.getElementById("txtHorFin"))){
							
							var d_ini = getDateFromString(document.getElementById("txtFchIni").value, document.getElementById("txtHorIni").value);
							var d_fin = getDateFromString(document.getElementById("txtFchFin").value, document.getElementById("txtHorFin").value);
							
							/*
							if((document.getElementById("txtFchIni").value == document.getElementById("txtFchFin").value) && (document.getElementById("txtHorIni").value < document.getElementById("txtHorFin").value)){
								document.getElementById("frmMain").action = "scheduler.SchedulerAction.do?action=confirm";
								submitForm(document.getElementById("frmMain"));
							}else if (new Date(document.getElementById("txtFchIni").value) < new Date(document.getElementById("txtFchFin").value)){
								document.getElementById("frmMain").action = "scheduler.SchedulerAction.do?action=confirm";
								submitForm(document.getElementById("frmMain"));
							}else{
								alert(FCH_FIN_MAY_FCH_INI);
							}
							*/
							if(d_ini < d_fin) {
								document.getElementById("frmMain").action = "scheduler.SchedulerAction.do?action=confirm";
								submitForm(document.getElementById("frmMain"));
							} else {
								alert(FCH_FIN_MAY_FCH_INI);
							}
						}else{
							alert(HOUR_FORMAT_ERROR);
						}
					//}
					
					/*else{
						document.getElementById("txtHorFin").value = "00:00";
						document.getElementById("frmMain").action = "scheduler.SchedulerAction.do?action=confirm";
						submitForm(document.getElementById("frmMain"));
					}
					*/
				}else{
					document.getElementById("frmMain").action = "scheduler.SchedulerAction.do?action=confirm";
					submitForm(document.getElementById("frmMain"));
				}
			}else{
				alert(HOUR_FORMAT_ERROR);				
			}
		}else{
			alert(MSG_INVALID_NODE_NAME);
		}
	}
}

function checkNodeName(){
	if (DISTRIBUTED_SCHEDULER){
		if (document.getElementById("radSelected").value == 2){
			if (document.getElementById("txtExeNode").value == ""){
				return false;
			}
		}
	}
	return true;
}

function btnExit_click(){
var msg = confirm(GNR_PER_DAT_ING);
	if (msg) {
		splash();
	}
}

function btnBack_click() {
var msg = confirm(GNR_PER_DAT_ING);
	if (msg) {
		document.getElementById("frmMain").action = "scheduler.SchedulerAction.do?action=backToList";
		submitForm(document.getElementById("frmMain"));
	}
}

function reloadPage() {
	document.getElementById("frmMain").action = "scheduler.SchedulerAction.do?action=reload";
	submitForm(document.getElementById("frmMain"));
}



var lastSelection = null;

function up_click() {
	if ((lastSelection != null) && (lastSelection.rowIndex > 1)) {
		swap(lastSelection.rowIndex-2,lastSelection.rowIndex - 1);
	}
}

function down_click() {
	if ((lastSelection != null) && (lastSelection.rowIndex < tblParamsBody.rows.length)) {
		swap(lastSelection.rowIndex - 1,lastSelection.rowIndex);
	}
}

function swap(pos1, pos2) {
	tblParamsBody.rows(pos1).swapNode(tblParamsBody.rows(pos2));
}


function btnAdd_click() {
	var oTd0 = document.createElement("TD"); 
	var oTd1 = document.createElement("TD"); 
		
	oTd0.innerHTML = "<input type='checkbox' name='chkSel'>";
	oTd0.align="center";
		
		
	oTd1.innerHTML = "<input type='text' name='txtParam'  size=50 maxlength=255>";
	oTd1.align="center";
		
	var oTr = document.createElement("TR");
	oTr.appendChild(oTd0);
	oTr.appendChild(oTd1);
	if (document.addEventListener) {
    	oTr.addEventListener("click", selectRow, false);
	}else{
		oTr.attachEvent("onclick", selectRow);
	}
	document.getElementById("gridParams").addRow(oTr);
}


function btnDel_click() {
	document.getElementById("gridParams").removeSelected();
}

function findRow(e) {
	if (e.tagName == "TR" && e.rowIndex!=0) {
		return e;
	} else if (e.tagName == "BODY") {
		return null;
	} else {
		return findRow(e.parentNode);
	}
}

function deselectRowOrCell(r) {
  r.className = r.orgClassName;
  r.selected=false;
}

function selectRowOrCell(r) {
  r.orgClassName = r.className;
  r.className = "trSelected";
  r.selected=true;
}

function selectRow() {
	var e, r, c;
  	e = window.event.srcElement;

  	if (e.tagName == "TR") {
    	r = findRow(e);
		if (r != null) {
	      	if (lastSelection != null) {
	        	deselectRowOrCell(lastSelection);
	      	}
	      	selectRowOrCell(r);
	      	lastSelection = r;
    	}
	} else {
		c = findCell(e);
		if (c != null) {
			if (lastSelection != null) {
				deselectRowOrCell(lastSelection);
			}
			selectRowOrCell(c);
			lastSelection = c;
		}
	}

	window.event.cancelBubble = true;
}

function findCell(e) {
	if (e.tagName == "TD") {
		return findRow(e.parentNode);
	} else if (e.tagName == "BODY") {
		return null;
	} else {
		return findCell(e.parentNode);
	}
}