function btnAddPool_click(envId) {
	var rets = openModal("/programs/modals/pools.jsp?showAutogenerated=false&showOnlyEnv=true&envId=" + envId + "&showGlobal=true",500,350);
	rets.onclose=function(){
		addObject(rets.returnValue,false);
	}
}

function btnAddUsr_click() {
	var rets = openModal("/programs/modals/users.jsp",500,300);
	rets.onclose=function(){
		addObject(rets.returnValue,true);
	}
}

function addObject(rets, isUser) {
	if (rets != null) {
		for (j = 0; j < rets.length; j++) {
			var ret = rets[j];
			var addRet = true;

			trows=document.getElementById("tskSchPrivGrid").rows;
			for (i=1;i<trows.length && addRet;i++) {
				if (trows[i].getElementsByTagName("TD")[3].getElementsByTagName("INPUT")[4].value == ret[0]) {
					addRet = false;
				}
				//Arreglamos los values de los inputs (por si se borro una fila)
				trows[i].getElementsByTagName("TD")[3].getElementsByTagName("INPUT")[0].value = i;
				trows[i].getElementsByTagName("TD")[3].getElementsByTagName("INPUT")[1].value = i;
				trows[i].getElementsByTagName("TD")[3].getElementsByTagName("INPUT")[2].value = i;
				trows[i].getElementsByTagName("TD")[3].getElementsByTagName("INPUT")[3].value = i;												
			}
			
			if (addRet) {
				var tr=trows[0].cloneNode(true);
				tr.setAttribute("cantDelete","");
				var tds=tr.getElementsByTagName("TD");
				var oTd0 = tds[0]; 
				var oTd1 = tds[1]; 
				var oTd2 = tds[2]; 
				var oTd3 = tds[3];
				oTd0.getElementsByTagName("INPUT")[0].style.visibility="visible";
				oTd0.getElementsByTagName("INPUT")[0].value = ret[0]; //usrLogin o poolId
				if (isUser) {
					oTd1.getElementsByTagName("DIV")[0].style.backgroundImage=("url(" + URL_STYLE_PATH+ "/images/user.gif)");
					oTd1.getElementsByTagName("DIV")[0].style.backgroundRepeat="no-repeat";
					oTd2.innerHTML = ret[1];//usrName
				} else {
					oTd1.getElementsByTagName("DIV")[0].style.backgroundImage=("url(" + URL_STYLE_PATH+ "/images/pool.gif)");
					oTd1.getElementsByTagName("DIV")[0].style.backgroundRepeat="no-repeat";
					oTd2.innerHTML = ret[1];//poolName
				}
				var rType;
				if (isUser) {
					rType = "user";
				} else {
					rType = "pool";
				}
				
				var permRead = "";
				var permMod = "";
				var permQry = "";
				var permReg = "";
		
				var str = "";
				if (document.getElementById("usePrjPerms").checked){
					str += "<input type='checkbox' id='chkRead' disabled name='chkRead' onclick='clickOnRead(this)' value='" + (trows.length + j) + "'>" + LBL_PERM_READ + "</input>";
					str += "<input type='checkbox' id='chkModify' disabled onclick='clickOnModify(this)' name='chkModify' value='" + (trows.length + j) + "'>" + LBL_PERM_UPDATE + "</input>";				
				}else{
					str += "<input type='checkbox' id='chkRead' name='chkRead' onclick='clickOnRead(this)' checked value='" + (trows.length + j) + "'>" + LBL_PERM_READ + "</input>";
					str += "<input type='checkbox' id='chkModify' onclick='clickOnModify(this)' name='chkModify' value='" + (trows.length + j) + "'>" + LBL_PERM_UPDATE + "</input>";				
				}
				str += "<input type='checkbox' id='chkQuery' onclick='clickOnQuery(this)' name='chkQuery' value='" + (trows.length + j) + "'>" + LBL_PERM_QUERY + "</input>";
				str += "<input type='checkbox' id='chkRegen' onclick='clickOnRegen(this)' name='chkRegen' value='" + (trows.length + j) + "'>" + LBL_PERM_REGEN + "</input>";
				str += "<input type='hidden' id='objValue' value='" + ret[0] + "' name='objValue' />";
				str += "<input type='hidden' id='type' value=" + rType + " name='type' />";
				
				oTd3.innerHTML = str;

				var oTr = document.createElement("TR");
				oTr.appendChild(oTd0);
				oTr.appendChild(oTd1);
				oTr.appendChild(oTd2);
				oTr.appendChild(oTd3);
				document.getElementById("tskSchPrivGrid").addRow(oTr);
				document.getElementById("tskSchPrivGrid").updateScroll();
			}
		}
	}		
}


function btnDelPriv_click() {
	var oRows=document.getElementById("tskSchPrivGrid").selectedItems;
	for(var i=(oRows.length-1);(i>=0);i--){
		if(oRows[i].getAttribute("cantDelete")!="true"){
			oRows[i].parentNode.removeChild(oRows[i]);
			document.getElementById("tskSchPrivGrid").updateScroll();
		}
		oRows[i].style.height="0px";
	}
	if (document.getElementById("tskSchPrivGrid").rows.length==1){
		document.getElementById("chkRead").checked = true;
		document.getElementById("chkModify").checked = true;
	}
}

function clickOnModify(modify){
	var read=modify.parentNode.getElementsByTagName("INPUT")[0];
	if (modify.checked){
		read.checked = true;
	}
	if (document.getElementById("tskSchPrivGrid").rows.length==1){
		modify.checked = true;
	}
}

function clickOnRead(read){
	var modify=read.parentNode.getElementsByTagName("INPUT")[1];
	if (modify.checked){
		read.checked = true;
	}
	if (document.getElementById("tskSchPrivGrid").rows.length==1){
		read.checked = true;
	}
}

function clickOnQuery(query){
	var regen=query.parentNode.getElementsByTagName("INPUT")[3];
	if (regen.checked){
		query.checked=true;
	}
}

function clickOnRegen(regen){
	var query = regen.parentNode.getElementsByTagName("INPUT")[2];
	if (regen.checked){
		query.checked = true;
	}
}

function chkUsePrjPerms() {
	if (document.getElementById("usePrjPerms").checked){ //Si el checkBox esta clickeado
		var msg = confirm(MSG_PERM_READ_MOD_WILL_BE_LOST);
		if (msg) {
			//Desclickeamos y deshabilitamos todos los check de lectura/modificacion
			var oRows = document.getElementById("tskSchPrivGrid").rows;
			for(var i=0; i<oRows.length;i++){
				var td = oRows[i].getElementsByTagName("TD");
				//Modo lectura
				td[3].getElementsByTagName("INPUT")[0].checked = false;
				td[3].getElementsByTagName("INPUT")[0].disabled = true;
				//Modo escritura
				td[3].getElementsByTagName("INPUT")[1].checked = false;
				td[3].getElementsByTagName("INPUT")[1].disabled = true;
			}
		}else{ //desclikeamos el checkbox
			document.getElementById("usePrjPerms").checked = false;
		}
	}else{ //Si el checkbox no esta clickeado
		//Habilitamos todos los check de lectura/modificacion
		var oRows = document.getElementById("tskSchPrivGrid").rows;
		for(var i=0; i<oRows.length;i++){
			var td = oRows[i].getElementsByTagName("TD");
			//Modo lectura
			td[3].getElementsByTagName("INPUT")[0].disabled = false;
			//Modo escritura
			td[3].getElementsByTagName("INPUT")[1].disabled = false;
		}
	}
}
