<%@page import="biz.statum.apia.web.bean.query.OffLineBean"%><%@page import="biz.statum.apia.web.action.query.OffLineAction"%><%@page import="biz.statum.sdk.util.HttpServletRequestResponse"%><%@include file="../../includes/startInc.jsp" %><html lang="<%=biz.statum.apia.web.bean.BasicBeanStatic.getUserDataStatic(request).getLangCode()%>"><head><%@include file="../../includes/headInclude.jsp" %><script type="text/javascript" src="<system:util show="context" />/page/query/offline/list.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminFav.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/campaigns.js"></script><script type="text/javascript">
		var URL_REQUEST_AJAX = '/apia.query.OffLineAction.run';
		var ADDITIONAL_INFO_IN_TABLE_DATA  = false;
		var MSG_NO_DOWNLOAD = '<system:label show="text" label="msgGenRegNoDown" />';
		var MSG_NO_VIEW = '<system:label show="text" label="msgGenRegNoView" />';
		
		<%
		HttpServletRequestResponse http = new HttpServletRequestResponse(request,response);
		OffLineBean bean = OffLineAction.staticRetrieveBean(http, false);
		%>
		
		var FROM_MINISITE = <%=bean.getUserData(http).isFromMinisite()%>;
	</script></head><body><div class="body" id="bodyDiv"><div class="optionsContainer" id="optionsContainer"><system:campaign inLogin="false" inSplash="false" location="verticalUp" /><%@include file="../common/panelInfo.jsp" %><% if(!bean.getUserData(http).isExternalMode()) { %><div class="fncPanel options"><div class="title"><system:label show="text" label="titActions"/></div><div class="content"><div id="btnCloseTab" class="button" title="<system:label show="tooltip" label="btnClose" />"><system:label show="text" label="btnClose" /></div></div></div><% } %><div class="fncPanel options lastOptions"><div class="title"><system:label show="text" label="mnuOpc" /></div><div class="content"><div id="optionDownload" class="button suggestedAction hidden" title="<system:label show="tooltip" label="btnDow"/>"><system:label show="text" label="btnDow"/></div><div id="optionView" class="button hidden" title="<system:label show="tooltip" label="btnView"/>"><system:label show="text" label="btnView"/></div></div><div class="clear"></div></div><system:campaign inLogin="false" inSplash="false" location="verticalDown" /></div><div class="gridContainer" id="gridContainer"><system:campaign inLogin="false" inSplash="false" location="horizontalUp" /><div class="gridHeader" id="gridHeader"><!-- Cabezal y filtros --><table><thead><tr id="trOrderBy" class="header"><th title="<system:label show="tooltip" label="lblFec" />"><div style="width: 150px"><system:label show="text" label="lblFec" /></div></th><th title="<system:label show="tooltip" label="lblType" />"><div style="width: 300px"><system:label show="text" label="lblType" /></div></th></tr></thead></table></div><div class="gridBody" id="gridBody"><!-- Cuerpo de la tabla --><table><thead><tr><th width="150px"></th><th width="300px"></th></tr></thead><tbody class="tableData" id="tableData"></tbody></table></div><div class="gridFooter"><div class="navButtons"><div class="pGroup"><div id="navRefresh" class="pButton btnRefresh"></div></div></div></div><system:campaign inLogin="false" inSplash="false" location="horizontalDown" /></div></div><%@include file="../../includes/footer.jsp" %></body></html>
