function initPermissions(hideUsePrjPerms) {
	var usePrjPerms = $('usePrjPerms');
	var cmbProject = $('cmbProject');
	var prmAddPool = $('prmAddPool');

	if (prmAddPool) {
		prmAddPool.addEvent("click", function(e) {
			e.stop();
			//setear variables de configuracion del modal de grupos
			POOLMODAL_SHOWAUTOGENERATED = true;
			POOLMODAL_SHOWNOTAUTOGENERATED = true;
			POOLMODAL_SHOWGLOBAL = true;
			POOLMODAL_SHOWCURRENTENV = true;
			ADDITIONAL_INFO_IN_TABLE_DATA = false;
			//abrir modal
			showPoolsModal(prmProcessPoolsModalReturn);
		});
	}
	
	if (cmbProject) {
		cmbProject.usePrjPerms = usePrjPerms;
		cmbProject.prmAddPool = prmAddPool;
		cmbProject.addEvent('change', function(etv){
			if (this.selectedIndex == 0) {
				this.usePrjPerms.checked = false;
				this.usePrjPerms.disabled = true;
				prmAddPool.style.display = '';
			} else {
				this.usePrjPerms.disabled = false;
				showConfirm(MSG_USE_PROY_PERMS,GNR_TIT_WARNING,changeProjectConfirm,"modalWarning");
			}
		});
		usePrjPerms.disabled = cmbProject.selectedIndex == 0;
	} else {
		usePrjPerms.disabled = true;
	}
	
	usePrjPerms.addEvent('click', function(evt){
		if (this.checked) {
			showConfirm(MSG_PERM_WILL_BE_LOST,GNR_TIT_WARNING,changePrjPermConfirm,"modalWarning");
		} else {
			prmAddPool.style.display = '';
		}
	});
	
	
	initPoolMdlPage();
	
	var request = new Request({
		method: 'post',
		url: CONTEXT + URL_REQUEST_AJAX + '?action=loadPermissions&isAjax=true' + TAB_ID_REQUEST,
		onRequest: function() { },
		onComplete: function(resText, resXml) { 
			modalProcessXml(resXml);
			
			initAdminModalHandlerOnChangeHighlight($('projectPermissions'));
			initAdminModalHandlerOnChangeHighlight($('prmPoolContainter'));
		}
	}).send();
	
	if (hideUsePrjPerms){ $('projectPermissions').setStyle("display","none"); }
}

function changePrjPermConfirm(result){
	var prmAddPool = $('prmAddPool');
	var cmbProject = $('cmbProject');
	if (result) {
		prmAddPool.style.display = 'none';
		//getActionElementsIds('prmPoolContainter').each(function(ele) {$(ele).destroy(); });
		getActionElements('prmPoolContainter').each(function(ele) {ele.destroy(); });
	} else {
		cmbProject.checked = false;
		prmAddPool.style.display = '';
	}
}

function changeProjectConfirm(result){
	var prmAddPool = $('prmAddPool');
	var usePrjPerms = $('usePrjPerms');
	if (result) {
		prmAddPool.style.display = 'none';
		//getActionElementsIds('prmPoolContainter').each(function(ele) {$(ele).destroy(); });
		getActionElements('prmPoolContainter').each(function(ele) {ele.destroy(); });
		usePrjPerms.checked = true;
	} else {
		usePrjPerms.checked = false;
		prmAddPool.style.display = '';
	}
}

function prmProcessPoolsModalReturn(ret) {
	ret.each(function(e){
		var text = e.getRowContent()[0];
		var id = e.getRowId();
		
		fncPersCreateNewElement(text, id, false);
	});
}

function fncPersLoadPools() {
	var ajaxCallXml = getLastFunctionAjaxCall();
	
	//var aRows = ajaxCallXml.getChildren('rows')[0];
	var aRows = ajaxCallXml.childNodes[0]; //IE friendly
	var useProject = aRows.getAttribute('useProject');
	var globalRead = aRows.getAttribute('globalRead');
	var globalWrite = aRows.getAttribute('globalWrite');

	$('usePrjPerms').checked = "true" == useProject;
	
	if (!SET_DEFAULT_VALUE_CMB){
		$('selPerAllPoolPerm').selectedIndex = ("true" == globalWrite) ? 2 : ("true" == globalRead) ? 1 : 0;
	} else {
		$('selPerAllPoolPerm').value = DEFAULT_VALUE_CMB;
		SET_DEFAULT_VALUE_CMB = false;
		DEFAULT_VALUE_CMB = "";
	}
	
	$('prmAddPool').style.display = $('usePrjPerms').checked ? 'none' : '';
	
	if (! $('usePrjPerms').checked) {
		//var rows = aRows.getChildren('row');
		var rows = aRows.childNodes; //IE friendly
		
		if (rows != null) {
			for (var i = 0; i < rows.length; i++) {
				var aRow = rows[i];
				var xmlCells = aRow.getElementsByTagName('cell');
				
				var poolId = xmlCells.item(0).firstChild.nodeValue;
				var poolName = xmlCells.item(1).firstChild.nodeValue;
				var canUpdate = xmlCells.item(2).firstChild.nodeValue;
				
				fncPersCreateNewElement(poolName, poolId, canUpdate == "true");
			}
		}
	}
}

function fncPersCreateNewElement(name, id, checked) {
	var content = addActionElement($('prmPoolContainter'),name, id, "hidPerPoolId");
	if (content == null) return;
	
	new Element('span.checkcontainer', {html: ' ' + LBL_CAN_UPDATE + ': '}).inject(content);
	var checkbox = new Element('input', {type: 'checkbox', name: 'chkPerPoolUpdate' + id, value: 'true'}).inject(content);
	checkbox.addEvent('click', function(evt){ evt.stopPropagation(); });
	if (checked) checkbox.checked = true;
	
	if (DISABLE_ALL_PERM){
		content.removeEvents("click");
		checkbox.disabled = true;
	}
}

var DISABLE_ALL_PERM = false;
function disableAllPermissionsPage(){
	DISABLE_ALL_PERM = true;
	var permContent = $('permContent');
	permContent.getElements("input").each(function(input){
		input.disabled = true;
		input.readOnly = true;
		input.addClass("readonly");
	});
	permContent.getElements("select").each(function(select){
		select.disabled = true;
		select.readOnly = true;
		select.addClass("readonly");
	});
	$('prmAddPool').removeEvents("click");	
	permContent.getElements("div.option").each(function(option){
    	option.removeEvents('click');
    });	 
}

var SET_DEFAULT_VALUE_CMB = false;
var DEFAULT_VALUE_CMB = "";
function setCmbPermDefaultValue(value){
	SET_DEFAULT_VALUE_CMB = true;
	DEFAULT_VALUE_CMB = value;
	var cmb = $('selPerAllPoolPerm');
	if (cmb){ 
		cmb.value = "2";
	}
}

function verifyPermissions(){
	if (!$('usePrjPerms').checked){ //Si no se usan los permisos del proyecto
		//Verificamos si almenos una persona tiene acceso de modificacion
		var someoneCanModify = false;
//		getActionElementsIds('prmPoolContainter').each(function(ele) {
//			if( $(ele).getChildren('input')[1].checked){
//				someoneCanModify = true;
//			}
//		});
		getActionElements('prmPoolContainter').each(function(ele) {
			if(ele.getChildren('input')[1].checked) {
				someoneCanModify = true;
			}
		});
		if($('selPerAllPoolPerm').value == 2){
			someoneCanModify = true;
		}
		if (!someoneCanModify){
			showMessage(MSG_PERMISSIONS_ERROR,null,'modalWarning');	
			return false;
		}
	}
	return true;
}