<%@page import="com.dogma.vo.*"%><%@page import="com.dogma.*"%><%@page import="java.util.*"%><%@include file="../../../../components/scripts/server/startInc.jsp" %><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.query.TaskSchedulerMonitorBean"></jsp:useBean><%

Collection tskSchNumbers = dBean.getTskSchNumbers();
TaskSchedulerVo selTaskSchVo = dBean.getTaskSchedulerVo();
boolean canQuery = "true".equals(request.getParameter("canQuery"));
boolean canResched = "true".equals(request.getParameter("canResched"));
%><%@page import="com.dogma.util.DogmaUtil"%><%@page import="com.dogma.vo.custom.TaskSchedulerMonitorVo"%><%@page import="com.st.util.DateUtil"%><%@page import="com.st.util.translator.TranslationManager"%><HTML><head><%@include file="../../../../components/scripts/server/headInclude.jsp" %></head><body onload="setNumericFields()"><%//Mostramos el filtro %><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,"titTskSchQryResched")%></TD><TD></TD></TR></TABLE><div id="divContent"><form id="frmMain" name="frmMain" method="POST"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtGenData")%></DIV><table class="tblFormLayout"><tr><td align="right" style="width:20%;" title="<%=LabelManager.getToolTip(labelSet,"lblScheduler")%>"><%=LabelManager.getNameWAccess(labelSet,"lblScheduler")%>:</td><td align="left"><select name="cmbTskSch" id="cmbTskSch" onchange="cmbTskSchChange()"><option value="0" <%=(selTaskSchVo==null)?"selected":"" %>></option><% Iterator itTskSched = dBean.getTaskSchedulers().iterator();
			    		   while (itTskSched.hasNext()){
							   	TaskSchedulerVo tskSchVo = (TaskSchedulerVo)itTskSched.next();%><option value="<%=tskSchVo.getTskSchId()%>"% <%=(selTaskSchVo!=null && selTaskSchVo.getTskSchId().intValue()==tskSchVo.getTskSchId().intValue())?"selected":"" %>><%=tskSchVo.getTskSchTitle()%></option><%}%></select></td></tr></table><%if (selTaskSchVo!=null){%><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtProFil")%></DIV><table class="tblFormLayout"><tr><td align="right" style="width:20%;" title="<%=LabelManager.getToolTip(labelSet,"lblProTit")%>"><%=LabelManager.getNameWAccess(labelSet,"lblProTit")%>:</td><td><select name="txtProTitle" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblProTit")%>"><option value=""></option><%Collection procs = dBean.getAllProcess(uData.getEnvironmentId());
						if(procs != null){
							Iterator iterProc = procs.iterator();
							ProcessVo pVo = null;
							String originalProcTitle = "";
							while(iterProc.hasNext()){
								pVo = (ProcessVo)iterProc.next();
								pVo.setLanguage(uData.getLangId());
								originalProcTitle = pVo.getProTitle();
								TranslationManager.setTranslationByNumber(pVo);%><option value="<%=originalProcTitle%>"  <%=originalProcTitle.equals(dBean.getFilterProTitle())?"selected":""%>><%=pVo.getProTitle()%></option><%}
						}%></select></td><td align="right" title="<%=LabelManager.getToolTip(labelSet,"lblMonInstProNroReg")%>"><%=LabelManager.getNameWAccess(labelSet,"lblMonInstProNroReg")%>:</td><td><input name="txtNamPre" maxlength="50" size="5" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblMonInstProNroReg")%>" type="text" value="<%=dBean.fmtStr(dBean.getFilterProInstPre())%>"><input name="txtNamNum" maxlength="11" size="7" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblMonInstProNroReg")%>" type="text" value="<%=(dBean.getFilterProInstNum()!=null)?dBean.getFilterProInstNum().intValue():""%>" class="txtNumeric"><input name="txtNamPos" maxlength="50" size="5"accesskey="<%=LabelManager.getAccessKey(labelSet,"lblMonInstProNroReg")%>" type="text" value="<%=dBean.fmtStr(dBean.getFilterProInstPos())%>"></td></tr></table><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtTskSchFil")%></DIV><table class="tblFormLayout"><tr><td align="right" style="width:20%;" title="<%=LabelManager.getToolTip(labelSet,"lblActDateBetween")%>"><%=LabelManager.getNameWAccess(labelSet,"lblActDateBetween")%>:</td><td><input type=text name="txtFchFrom" p_calendar="true" class="txtDate" value="<%=(dBean.getFilterDateFrom()!=null && !"".equals(dBean.getFilterDateFrom()))?dBean.getFilterDateFrom():""%>" p_mask="<%=DogmaUtil.getHTMLDateMask(dBean.getEnvId(request))%>" size="10" maxlength="10" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblActDate")%>" <%if(selTaskSchVo==null){%>disabled<%}%>><input type=text name="txtHorFrom" maxlength=5 size=5 p_mask="<%=DogmaUtil.getHTMLTimeMask()%>" value="<%=(dBean.getFilterHourFrom()!=null && !"".equals(dBean.getFilterHourFrom()))?dBean.getFilterHourFrom():""%>" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblTime")%>" <%if(selTaskSchVo==null){%>disabled<%}%> >
					   	-
					   	<input type=text name="txtFchTo" p_calendar="true" class="txtDate" value="<%=(dBean.getFilterDateTo()!=null && !"".equals(dBean.getFilterDateTo()))?dBean.getFilterDateTo():""%>" p_mask="<%=DogmaUtil.getHTMLDateMask(dBean.getEnvId(request))%>" size="10" maxlength="10" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblActDate")%>" <%if(selTaskSchVo==null){%>disabled<%}%>><input type=text name="txtHorTo" maxlength=5 size=5 p_mask="<%=DogmaUtil.getHTMLTimeMask()%>" value="<%=(dBean.getFilterHourTo()!=null && !"".equals(dBean.getFilterHourTo()))?dBean.getFilterHourTo():""%>" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblTime")%>" <%if(selTaskSchVo==null){%>disabled<%}%> ></td></tr><%Iterator itAtts = selTaskSchVo.getTskSchAttributes().iterator();
				String numericFields = "";
				if (selTaskSchVo.getTskSchAttributes()!=null && selTaskSchVo.getTskSchAttributes().size()>0){
					int count = 1;
					while (itAtts.hasNext()){
						TskSchAttributeVo tskSchAttVo = (TskSchAttributeVo) itAtts.next();
						if (count==1){%><tr><%}%><td align="right"><%=tskSchAttVo.getAttLabel()%>:</td><td class="readOnly"><%if (AttributeVo.TYPE_STRING.equals(tskSchAttVo.getAttType())){%><input name="txtAtt_<%=tskSchAttVo.getAttId()%>" <%if (tskSchAttVo.getTskSchAttFlag(TskSchAttributeVo.FLAG_ATT_REQUIRED)){%> p_required="true" <%}%> value="<%=(tskSchAttVo.getFilterValue()!=null && !"".equals(tskSchAttVo.getFilterValue()))?tskSchAttVo.getFilterValue():""%>"><%}else if(AttributeVo.TYPE_NUMERIC.equals(tskSchAttVo.getAttType()) || AttributeVo.TYPE_INT.equals(tskSchAttVo.getAttType())){
						   		if ("".equals(numericFields)){
						   			numericFields = "txtAtt_" + tskSchAttVo.getAttId();
						   		}else{
						   			numericFields += ";txtAtt_" + tskSchAttVo.getAttId();						   		
						   		}%><input name="txtAtt_<%=tskSchAttVo.getAttId()%>" <%if (tskSchAttVo.getTskSchAttFlag(TskSchAttributeVo.FLAG_ATT_REQUIRED)){%> p_required="true" <%}%> p_numeric="true" value="<%=(tskSchAttVo.getFilterValue()!=null && !"".equals(tskSchAttVo.getFilterValue()))?tskSchAttVo.getFilterValue():""%>"><%}else if(AttributeVo.TYPE_DATE.equals(tskSchAttVo.getAttType())){%><input type="text" name="txtAtt_<%=tskSchAttVo.getAttId()%>" <%if (tskSchAttVo.getTskSchAttFlag(TskSchAttributeVo.FLAG_ATT_REQUIRED)){%> p_required="true" <%}%> p_calendar="true" class="txtDate" p_mask="<%=DogmaUtil.getHTMLDateMask(dBean.getEnvId(request))%>" size="10" maxlength="10" value="<%=(tskSchAttVo.getFilterValue()!=null && !"".equals(tskSchAttVo.getFilterValue()))?tskSchAttVo.getFilterValue():""%>" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblDate")%>"><%}%></td><%
						if (count==3){
							count = 1;%></tr><%}else{
							count++;
						}
					}
					if (count>1){%></tr><%}%><%}%><tr><td><input type="hidden" name="hiddNumericFields" id="hiddNumericFields" value="<%=numericFields%>"/></td></tr><table class="tblFormLayout"><tr style="width=100%"><td></td><td align="right"><button type="button" onclick="btnSearch_click()" title="<%=LabelManager.getToolTip(labelSet,"btnBus")%>" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnBus")%>"><%=LabelManager.getNameWAccess(labelSet,"btnBus")%></button><button type="button" onclick="btnReset_click()" title="<%=LabelManager.getToolTip(labelSet,"btnRes")%>" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnRes")%>"><%=LabelManager.getNameWAccess(labelSet,"btnRes")%></button></td></tr></table><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtWaitingTasks")%></DIV><div type="grid" id="gridList" style="height:<%=Parameters.SCREEN_LIST_SIZE%>px"><table  width="500px" cellpadding="0" cellspacing="0"><thead><tr><th style="width:0px;display:none;" title="<%=LabelManager.getToolTip(labelSet,"lblSel")%>"></th><th min_width="100px" style="width:100px" title="<%=LabelManager.getToolTip(labelSet,"lblMonInstProNroReg")%>"><%=LabelManager.getName(labelSet,"lblMonInstProNroReg")%></th><th min_width="100px" style="min-width:100px;width:60%" title="<%=LabelManager.getToolTip(labelSet,"lblPro")%>"><%=LabelManager.getName(labelSet,"lblPro")%></th><th min_width="100px" style="min-width:100px;width:40%" title="<%=LabelManager.getToolTip(labelSet,"lblTask")%>"><%=LabelManager.getName(labelSet,"lblTask")%></th><th min_width="100px" style="width:100px" title="<%=LabelManager.getToolTip(labelSet,"lblActDate")%>"><%=LabelManager.getName(labelSet,"lblActDate")%></th><th min_width="100px" style="width:100px" title="<%=LabelManager.getToolTip(labelSet,"lblActHour")%>"><%=LabelManager.getName(labelSet,"lblActHour")%></th><% itAtts = selTaskSchVo.getTskSchAttributes().iterator();
									while (itAtts.hasNext()){
										TskSchAttributeVo tskSchAttVo = (TskSchAttributeVo) itAtts.next();%><th min_width="100px" style="width:100px" title="<%=tskSchAttVo.getAttDesc()%>"><%=tskSchAttVo.getAttLabel()%></th><%}
								%></tr></thead><tbody><% Iterator itNumbers = dBean.getTskSchNumbers().iterator();
				   			   int i=0;
				   			   while (itNumbers.hasNext()){
				   			   		TaskSchedulerMonitorVo tskSchNumVo = (TaskSchedulerMonitorVo) itNumbers.next();
					   			   	HashMap attValues = tskSchNumVo.getAttValuesHash();
				   			   		%><tr><td  style="width:0px;display:none;"><input type="hidden" id="idSel" name="chkSel<%=i%>"><input type="hidden" name="hidTskSchId<%=i%>" value="<%=dBean.fmtInt(tskSchNumVo.getTskSchId())%>"><input type="hidden" name="hidProInstId<%=i%>" value="<%=dBean.fmtInt(tskSchNumVo.getProInstId())%>"><input type="hidden" name="hidProId<%=i%>" value="<%=dBean.fmtInt(tskSchNumVo.getProId())%>"><input type="hidden" name="hidProVerId<%=i%>" value="<%=dBean.fmtInt(tskSchNumVo.getProVerId())%>"><input type="hidden" name="hidTskId<%=i%>" value="<%=dBean.fmtInt(tskSchNumVo.getTskId())%>"><input type="hidden" name="hidTskSchNumHor<%=i%>" value="<%=dBean.fmtInt(tskSchNumVo.getTskSchNumHor())%>"><input type="hidden" name="hidTskSchNumDay<%=i%>" value="<%=dBean.fmtInt(tskSchNumVo.getTskSchNumDay())%>"><input type="hidden" name="hidTskSchNumDte<%=i%>" value="<%=tskSchNumVo.getTskSchNumDte()%>"></td><td><%=dBean.fmtHTML(tskSchNumVo.getProcessIdentification())%></td><td style="min-width:100px"><%=dBean.fmtHTML(tskSchNumVo.getProName())%></td><td style="min-width:100px"><%=dBean.fmtHTML(tskSchNumVo.getTskName())%></td><td><%=dBean.fmtHTML(tskSchNumVo.getDteAct())%></td><td><%=dBean.fmtHTML(tskSchNumVo.getHorAct())%></td><% itAtts = selTaskSchVo.getTskSchAttributes().iterator();
										   while (itAtts.hasNext()){
												TskSchAttributeVo tskSchAttVoDef = (TskSchAttributeVo) itAtts.next();
												TskSchAttributeVo tskSchAttVoVal = (TskSchAttributeVo) attValues.get(tskSchAttVoDef.getAttId());
												if (tskSchAttVoVal!=null){
													if (tskSchAttVoVal.getAttNumValue()!=null){%><td><%=tskSchAttVoVal.getAttNumValue()%></td><%}else if (tskSchAttVoVal.getAttStrValue()!=null){%><td><%=tskSchAttVoVal.getAttStrValue()%></td><%}else if (tskSchAttVoVal.getAttDteValue()!=null){%><td><%=DateUtil.dateToString(tskSchAttVoVal.getAttDteValue())%></td><%}else{%><td></td><%}
												 }else{%><td></td><%}
											}
										   i++;%></tr><%}%></tbody></table></div></table><%} %></form></DIV><TABLE class="pageBottom"><COL class="col1" /><COL class="col2" /><TR><TD align="right"><% if (canResched){%><button type="button" onclick="btnReag_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnReagendar")%>" title="<%=LabelManager.getToolTip(labelSet,"btnReagendar")%>"><%=LabelManager.getNameWAccess(labelSet,"btnReagendar")%></button><%}%><button type="button" onclick="btnExit_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></HTML><%@include file="../../../../components/scripts/server/endInc.jsp" %><script language='javascript' src='<%=Parameters.ROOT_PATH%>/programs/query/monitor/taskScheduler/taskSchQuery.js'></script>