<%@page import="com.st.util.labels.LabelManager"%><%@page import="java.util.Iterator"%><%@page import="biz.statum.apia.web.action.control.LogAnalyzerAction"%><%@page import="biz.statum.apia.web.bean.control.LogAnalyzerBean"%><%@page import="com.dogma.vo.analyzer.AnalyzerConfiguration"%><%@include file="../../includes/startInc.jsp" %><html lang="<%=biz.statum.apia.web.bean.BasicBeanStatic.getUserDataStatic(request).getLangCode()%>"><head><%@include file="../../includes/headInclude.jsp" %><script type="text/javascript" src="<system:util show="context" />/page/control/logAnalyzer/init.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminActionsEdition.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/adminFav.js"></script><script type="text/javascript" src="<system:util show="context" />/page/includes/campaigns.js"></script><script type="text/javascript">
		var URL_REQUEST_AJAX 	= '/apia.control.LogAnalyzerAction.run';
		var TSK_LST				= '<system:label show="text" label="lblQryTypTas" forScript="true" />';
		var MSG_ERROR_DATE		= '<system:label show="text" label="msgIniBefEnd" forScript="true" />';
	</script></head><body><div id="exec-blocker"></div><div class="body" id="bodyDiv"><form id="frmData"><div class="optionsContainer"><system:campaign inLogin="false" inSplash="false" location="verticalUp" /><div class="fncPanel info"><div class="title"><system:label show="text" label="sbtAnaly" /><%@include file="../../includes/adminFav.jsp" %></div><div class="content divFncDescription"><div class="fncDescriptionImage" data-src="<system:edit show="value" from="theBean" field="fncImage"/>"></div><div id="fncDescriptionText"><system:label show="text" label="dscFncLogAna"/></div><div class="clear"></div></div></div><div class="fncPanel options"><div class="title"><system:label show="text" label="mnuOpc" /></div><div class="content"><div id="btnGen" class="button suggestedAction" title="<system:label show="tooltip" label="btnGen" />"><system:label show="text" label="btnGen" /></div><div class="clear"></div></div><div class="clear"></div></div><system:campaign inLogin="false" inSplash="false" location="verticalDown" /></div><div class="dataContainer"><div class='tabComponent' id="tabComponent"><div class="aTabHeader"><system:campaign inLogin="false" inSplash="false" location="horizontalUp" /></div><div class="aTab"><div class="tab"><system:label show="text" label="tabDatGen" /></div><div class="contentTab"><div class="fieldGroup"><div class="field  required"><label title="<system:label show="tooltip" label="lblAnaTimeFmt" />"><system:label show="text" label="lblAnaTimeFmt" />:</label><select name="anaTimeFromat" id="anaTimeFromat" ><option value="<%= AnalyzerConfiguration.TIME_MILISEC %>"	<system:edit show="ifValue" from="theBean" field="timeFormat" value="ms" >selected</system:edit>	><system:label show="text" label="lblTimeMilSec" /></option><option value="<%= AnalyzerConfiguration.TIME_SECOND %>"	<system:edit show="ifValue" from="theBean" field="timeFormat" value="ms" >selected</system:edit>	><system:label show="text" label="lblTimeSec" /></option><option value="<%= AnalyzerConfiguration.TIME_MINUTE %>"	<system:edit show="ifValue" from="theBean" field="timeFormat" value="ms" >selected</system:edit>	><system:label show="text" label="lblTimeMin" /></option></select></div><div class="field required"><label title="<system:label show="tooltip" label="txtAnaDateFrom" />"><system:label show="text" label="txtAnaDateFrom" />:</label><input type="text" name="anaDateFrom" id="anaDateFrom" class="  validate['required']" style="width:120px" value="<system:edit show="value" from="theBean" field="anaDateFrom"/>"></div><div class="field required"><label title="<system:label show="tooltip" label="txtAnaDateTo" />"><system:label show="text" label="txtAnaDateTo" />:</label><input type="text" name="anaDateTo" id="anaDateTo" class="  validate['required']" style="width:120px" value="<system:edit show="value" from="theBean" field="anaDateTo"/>"></div></div><div class="fieldGroup"><div class="title"><system:label show="text" label="sbtAnaOpc" /></div><%
									LogAnalyzerBean dBean = LogAnalyzerAction.getBean(request,response); 
									AnalyzerConfiguration configVo = dBean.getConfiguration();
									boolean addComment = true;
									for (Iterator it = configVo.getExcedeTimes().keySet().iterator(); it.hasNext(); ) {	 
										String key = (String) it.next();
										Double time = (Double) configVo.getExcedeTimes().get(key); 
										String name = com.dogma.analyzer.impl.BusClassOpenAnalyzer.getInstance().getName();
										if (! name.equals(key)) { %><div class="field required "><label title="<%=LabelManager.getToolTip(dBean.getUserDataStatic(request) ,"txtAna" + key)%>"><%=LabelManager.getName(dBean.getUserDataStatic(request) ,"txtAna" + key)%>:</label><input type="text" name="time<%= key %>" id="time<%= key %>" class="validate['digit']"  value="1000" maxlength="5"     ></div><%}
									} 
									%><div class="field fieldFull required"><label title="<system:label show="tooltip" label="txtAnaCommen1" />"><system:label show="text" label="txtAnaCommen1" /></label><input type="hidden" name="<%= com.dogma.analyzer.impl.BusClassOpenAnalyzer.getInstance().getName() %>" value="0"></div></div></div></div></div><system:campaign inLogin="false" inSplash="false" location="horizontalDown" /></div></form></div><%@include file="../../includes/footer.jsp" %></body></html>

