<%@page import="com.dogma.vo.*"%><%@page import="com.dogma.vo.custom.DocumentationVo"%><%@page import="com.dogma.vo.analyzer.*" %><%@page import="java.util.*" %><%@page import="com.dogma.util.*" %><%@include file="../../../components/scripts/server/startInc.jsp" %><HTML><head><%@include file="../../../components/scripts/server/headInclude.jsp" %></head><body><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.security.AnalyzerBean"></jsp:useBean><% AnalyzerConfiguration configVo = dBean.getConfiguration(); %><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,"titAnaly")%></TD><TD></TD></TR></TABLE><div id="divContent"><form id="frmMain" name="frmMain" method="POST"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtAnaly")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblAnaTimeFmt")%>"><%=LabelManager.getNameWAccess(labelSet,"lblAnaTimeFmt")%>:</td><td colspan=3><select p_required="true" name="anaTimeFromat" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblAnaTimeFmt")%>"><option value=""></option><option value="<%= AnalyzerConfiguration.TIME_MILISEC %>" <%= AnalyzerConfiguration.TIME_MILISEC.equals(configVo.getTimeFormat())?"selected":"" %>><%=LabelManager.getNameWAccess(labelSet,"lblTimeMilSec")%></option><option value="<%= AnalyzerConfiguration.TIME_SECOND %>" <%= AnalyzerConfiguration.TIME_SECOND.equals(configVo.getTimeFormat())?"selected":"" %>><%=LabelManager.getNameWAccess(labelSet,"lblTimeSec")%></option><option value="<%= AnalyzerConfiguration.TIME_MINUTE %>" <%= AnalyzerConfiguration.TIME_MINUTE.equals(configVo.getTimeFormat())?"selected":"" %>><%=LabelManager.getNameWAccess(labelSet,"lblTimeMin")%></option></select></td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"txtAnaDateFrom")%>"><%=LabelManager.getNameWAccess(labelSet,"txtAnaDateFrom")%>:</td><td><input type=text name="anaDateFrom" p_calendar="true" class="txtDate" p_mask="<%=DogmaUtil.getHTMLDateMask(dBean.getEnvId(request))%>" p_required="true" size="10" maxlength="10" accesskey="<%=LabelManager.getAccessKey(labelSet,"txtAnaDateFrom")%>" value="<%=dBean.fmtHTML(configVo.getDateFrom())%>"></td><td title="<%=LabelManager.getToolTip(labelSet,"txtAnaDateTo")%>"><%=LabelManager.getNameWAccess(labelSet,"txtAnaDateTo")%>:</td><td><input type=text name="anaDateTo" p_calendar="true" class="txtDate" p_mask="<%=DogmaUtil.getHTMLDateMask(dBean.getEnvId(request))%>" p_required="true" size="10" maxlength="10" accesskey="<%=LabelManager.getAccessKey(labelSet,"txtAnaDateTo")%>" value="<%=dBean.fmtHTML(configVo.getDateTo())%>"></td></tr></table><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtAnaOpc")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><%
				boolean addComment = true;
				for (Iterator it = configVo.getExcedeTimes().keySet().iterator(); it.hasNext(); ) { 
					String key = (String) it.next();
					Double time = (Double) configVo.getExcedeTimes().get(key); 
					String name = com.dogma.analyzer.impl.BusClassOpenAnalyzer.getInstance().getName();
					if (! name.equals(key)) { %><tr><td title="<%=LabelManager.getToolTip(labelSet,"txtAna" + key)%>"><%=LabelManager.getNameWAccess(labelSet,"txtAna" + key)%>:</td><td><input name="time<%= key %>" type="text" value="<%= dBean.fmtHTML(time) %>" p_required=true p_numeric='true' accesskey="<%= LabelManager.getAccessKey(labelSet,"txtAna" + key) %>"></td><%
							if (addComment) {%><td colspan="2" rowspan=""><%=LabelManager.getName(labelSet,"txtAnaCommen1")%><input type="hidden" name="<%= com.dogma.analyzer.impl.BusClassOpenAnalyzer.getInstance().getName() %>" value="0"></td><%
								addComment = false;
							}%></tr><%
					}
				} %></table><% if (dBean.isReportGenerated()) { %><DIV class="subTit"><%=LabelManager.getName(labelSet,"lblMigDownloadFile")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td></td><td><button onclick="downloadDocument()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnDow")%>" title="<%=LabelManager.getToolTip(labelSet,"btnDow")%>"><%=LabelManager.getNameWAccess(labelSet,"btnDow")%></button></td><td></td><td></td></tr></table><IFRAME name="idResult" id="idResult" height="0" width="0" frameborder="0" ></IFRAME><% } %></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD><button onclick="btnGen_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnGen")%>" title="<%=LabelManager.getToolTip(labelSet,"btnGen")%>"><%=LabelManager.getNameWAccess(labelSet,"btnGen")%></button><button onclick="btnExit_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><%@include file="../../../components/scripts/server/endInc.jsp" %><script language="javascript" src='<%=Parameters.ROOT_PATH%>/programs/security/analyzer/config.js'></script><% if (dBean.isReportGenerated()) { %><script language="javascript">
  
function downloadDocument() {
  document.getElementById("idResult").src="<%=Parameters.ROOT_PATH%>/programs/security/analyzer/download.jsp"
}
</script><% } %>