		<div type="tab" style="visibility:hidden" style="visibility:hidden;" tabTitle="<%=LabelManager.getToolTip(labelSet,"tabTskSchAtts")%>" tabText="<%=LabelManager.getName(labelSet,"tabTskSchAtts")%>"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtSchAttributes")%></DIV><div style="height:120px;" type="grid" id="tskSchAttGrid"><table width="500px" cellpadding="0" cellspacing="0"><thead class="fixedHeader"><tr><th style="width:0px;display:none;" title="<%=LabelManager.getToolTip(labelSet,"lblSel")%>">&nbsp;</th><th min_width="150px" style="width:150px" title="<%=LabelManager.getToolTip(labelSet,"lblNom")%>"><%=LabelManager.getName(labelSet,"lblNom")%></th><th min_width="150px" style="width:150px" title="<%=LabelManager.getToolTip(labelSet,"lblType")%>"><%=LabelManager.getName(labelSet,"lblType")%></th><th min_width="150px" style="min-width:150px;width:100%" title="<%=LabelManager.getToolTip(labelSet,"lblReq")%>"><%=LabelManager.getName(labelSet,"lblReq")%></th></tr></thead><tbody class="scrollContent"><%if  (tskSchVo.getTskSchAttributes() != null && tskSchVo.getTskSchAttributes().size()>0) {
								Iterator it = tskSchVo.getTskSchAttributes().iterator();
								int i = 0;
								while (it.hasNext()) {
									TskSchAttributeVo tskSchAttVo = (TskSchAttributeVo) it.next();%><tr style="100%"><td style="width:0px;display:none;" align="center"><input type='checkbox' name='chkAttSel'><input type='hidden' name='chkAtt' value="<%=tskSchAttVo.getAttId().intValue()%>"></td><td><%=dBean.fmtHTML(tskSchAttVo.getAttName())%><input type="hidden" id="attName" name="attName" value="<%=tskSchAttVo.getAttName()%>"/></td><td><select name="selAttType" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblType")%>"><option value="<%=TskSchAttributeVo.ATT_TYPE_ENTITY%>" 
		   											<%if (tskSchAttVo.getTskSchId()==null || TskSchAttributeVo.ATT_TYPE_ENTITY.equals(tskSchAttVo.getTskSchAttOwner())) {
		   												out.print ("selected");
		   											}%>
													><%=LabelManager.getName(labelSet,"lblEnt")%></option><option value="<%=TskSchAttributeVo.ATT_TYPE_PROCESS%>"
													<%if (TskSchAttributeVo.ATT_TYPE_PROCESS.equals(tskSchAttVo.getTskSchAttOwner())) {
		   												out.print ("selected");
		   											}%>
													><%=LabelManager.getName(labelSet,"lblPro")%></option></select></td><td style="min-width:150px"><input type="checkbox" id="chkAttReq" name="chkAttReq" value="<%=i%>" <%if (tskSchAttVo.getTskSchAttFlag(TskSchAttributeVo.FLAG_ATT_REQUIRED)){%> checked <%}%>></input></td></tr><%i++;
								}
							}%></tbody></table></div><table class="navBar" id="navBar"><COL class="col2"><tr><td><button type="button" type="button" onclick="btnLoadAtt_click(<%=tskSchVo.getEnvId().intValue()%>)" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnAgrAtt")%>" title="<%=LabelManager.getToolTip(labelSet,"btnAgrAtt")%>"><%=LabelManager.getNameWAccess(labelSet,"btnAgrAtt")%></button><button type="button" type="button" onclick="btnDel_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnEli")%>" title="<%=LabelManager.getToolTip(labelSet,"btnEli")%>"><%=LabelManager.getNameWAccess(labelSet,"btnEli")%></button></td></tr></table></div>