<%@page import="com.dogma.vo.*"%><%@page import="com.apia.core.CoreFacade"%><%@include file="../../../components/scripts/server/startInc.jsp" %><HTML><head><%@include file="../../../components/scripts/server/headInclude.jsp" %></head><body><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.administration.BPMNBean"></jsp:useBean><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,"titBPMN")%></TD><TD></TD></TR></TABLE><div id="divContent"><form id="frmMain" name="frmMain" method="POST" enctype="multipart/form-data"><DIV class="subTit"><%=LabelManager.getName(labelSet,"btnImportXPDL")%></DIV><div id="loadFromFile"><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr height="30px"></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"titRutaXpdl")%>"><%=LabelManager.getNameWAccess(labelSet,"titRutaXpdl")%>:</td><td colspan="3"><input type="FILE" p_required="true" length="150" name="txtUpload" size="70" accesskey="<%=LabelManager.getAccessKey(labelSet,"titRutaXpdl")%>" title="<%=LabelManager.getToolTip(labelSet,"lblBrowse")%>"></td><td></td><td></td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblTipImp")%>"><%=LabelManager.getNameWAccess(labelSet,"lblTipImp")%>:</td><td><select id="cmbType" name="cmbType" p_required="true"  accesskey="<%=LabelManager.getAccessKey(labelSet,"lblTipImp")%>"><option value="<%=LabelManager.getName(labelSet,"lblXpdlFacilis")%>" selected><%=LabelManager.getName(labelSet,"lblXpdlFacilis")%></option><option value="<%=LabelManager.getName(labelSet,"lblXpdlStd")%>"><%=LabelManager.getName(labelSet,"lblXpdlStd")%></option><option value="<%=LabelManager.getName(labelSet,"lblXpdlApia")%>"><%=LabelManager.getName(labelSet,"lblXpdlApia")%></option></select></td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblProEnt")%>"><%=LabelManager.getNameWAccess(labelSet,"lblProEnt")%>:</td><td><select id="cmbEnt" name="cmbEnt" p_required="true" onChange="cmbLoadEntInfo_change()" accesskey="<%=LabelManager.getAccessKey(labelSet,"titEnt")%>"><option value="<%=LabelManager.getName(labelSet,"lblProNewEnt")%>" selected><%=LabelManager.getName(labelSet,"lblProNewEnt")%></option><option value="<%=LabelManager.getName(labelSet,"lblProExiEnt")%>"><%=LabelManager.getName(labelSet,"lblProExiEnt")%></option><option value="<%=LabelManager.getName(labelSet,"lblProNoEnt")%>"><%=LabelManager.getName(labelSet,"lblProNoEnt")%></option></select></td><td>&nbsp;</td><td>&nbsp;</td></tr></table></div><div id="entInfo" style="display=none"><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td></td><td><input type="text" id="entName" name="entName" style="display=none"/></td></tr><tr><td></td><td><select id="busEnts" name="busEnts" accesskey="<%=LabelManager.getAccessKey(labelSet,"titEnt")%>" style="display=none"><% 
			   					Collection<BusEntityVo> busEntVos = dBean.getBusEntities(request);
			   					if (busEntVos != null && busEntVos.size() > 0) {
			   						for (BusEntityVo busEntVo : busEntVos) {
			   						%><option value="<%=busEntVo.getBusEntId()%>" ><%=busEntVo.getBusEntName()%></option><%	} 
			   					} %></select></td></tr></table></div></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD><button type="button" onclick="btnConf_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnCon")%>" title="<%=LabelManager.getToolTip(labelSet,"btnCon")%>"><%=LabelManager.getNameWAccess(labelSet,"btnCon")%></button><button type="button" onclick="btnBack_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnVol")%>" title="<%=LabelManager.getToolTip(labelSet,"btnVol")%>"><%=LabelManager.getNameWAccess(labelSet,"btnVol")%></button><button type="button" onclick="btnExit_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><%@include file="../../../components/scripts/server/endInc.jsp" %><script src="<%=Parameters.ROOT_PATH%>/programs/administration/process/importXPDL.js"></script><script language="javascript" >

var fromApia 	= "<%=LabelManager.getName(labelSet,"lblXpdlApia")%>";
var fromStd  	= "<%=LabelManager.getName(labelSet,"lblXpdlStd")%>";
var fromFacilis = "<%=LabelManager.getName(labelSet,"lblXpdlFacilis")%>";

var existEnt = "<%=LabelManager.getName(labelSet,"lblProExiEnt")%>"
var newEnt = "<%=LabelManager.getName(labelSet,"lblProNewEnt")%>"

</script><script>
cmbLoadEntInfo_change();
</script>