<%@page import="com.dogma.vo.*"%><%@include file="../../../components/scripts/server/startInc.jsp" %><HTML><head><%@include file="../../../components/scripts/server/headInclude.jsp" %></head><body><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.security.GroupBean"></jsp:useBean><%
PoolVo poolVo = dBean.getPoolVo();
%><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,dBean.isModeGlobal()?"titGru":"titGruEnv")%></TD><TD></TD></TR></TABLE><div id="divContent"><form id="frmMain" name="frmMain" method="POST"><div type ="tabElement" id="samplesTab" ontabswitched="tabSwitch()"<%=(request.getParameter("defaultTab")!=null?(" defaultTab='"+request.getParameter("defaultTab").toString()+"'"):"" )%>><div type="tab" style="visibility:hidden" style="visibility:hidden;" tabTitle="<%=LabelManager.getToolTip(labelSet,"tabProGen")%>" tabText="<%=LabelManager.getName(labelSet,"tabProGen")%>"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtDatGru")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td><%=LabelManager.getNameWAccess(labelSet,"lblNom")%>:</td><td><input name="txtName" p_required="true" maxlength="50" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblNom")%>" type="text" <%if(poolVo!=null) {%>value="<%=dBean.fmtStr(poolVo.getPoolName())%>"<%}%>></td><td></td><td></td></tr><tr><td><%=LabelManager.getNameWAccess(labelSet,"lblDes")%>:</td><td colspan=3><input name="txtDesc" maxlength="255" size=80 accesskey="<%=LabelManager.getAccessKey(labelSet,"lblDes")%>" type="text" <%if(poolVo!=null) {%>value="<%=dBean.fmtStr(poolVo.getPoolDesc())%>"<%}%>></td></tr><tr><%if(dBean.isModeGlobal()){%><td><%=LabelManager.getNameWAccess(labelSet,"lblTodEnv")%>:</td><td><input type="checkbox" name="chkTodEnv" onclick="chkTodEnv_change()" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblTodEnv")%>" <%if(poolVo!=null && poolVo.getPoolAllEnvs()!=null && poolVo.getPoolAllEnvs().intValue() == 1) {%> checked <%}%>></td><%}else{%><td></td><td></td><%}%><td title="<%=LabelManager.getToolTip(labelSet,"lblImage")%>"><%=LabelManager.getNameWAccess(labelSet,"lblImage")%>:</td><%String img=( "".equals(poolVo.getImgPath()) || poolVo.getImgPath()==null  )?"":poolVo.getImgPath();%><td><div onClick="openImagePicker(this)" style="cursor:pointer;cursor:hand;position:relative;width:50px;height:50px;background-image:url(<%=Parameters.ROOT_PATH+"/images/"%><%=img==""?"uploaded/poolicon.png":"uploaded/"+img%>)"><input type="hidden" name="txtProjImg" id="txtProjImg" value="<%=img%>" /></div></td></tr></table><div id="divx" <%if(!dBean.isModeGlobal()){%> style="display:none" <%}%>><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtEnv")%></DIV><div type="grid" id="gridEnv" style="height:100px"><table id="tblEnv" width="500px" cellpadding="0" cellspacing="0"><thead><tr><th style="width:0px;display:none;" title="<%=LabelManager.getToolTip(labelSet,"lblSel")%>"></th><th min_width="200px" style="min-width:200px;width:100%" title="<%=LabelManager.getToolTip(labelSet,"lblAmb")%>"><%=LabelManager.getName(labelSet,"lblAmb")%></th></tr></thead><tbody id="tblEnvBody"><%
									Collection col = dBean.getEnvs();
									if(col!=null){
										for (Iterator it = col.iterator(); it.hasNext(); ) { 
											Integer i = (Integer)it.next(); %><tr><td style="width:0px;display:none;"><input type='hidden' name='chkSelect'><input type='hidden' name='chkEnv' value="<%=i%>"></td><td style="min-width:200px"><%=dBean.fmtStr(dBean.getEnvName(i))%></td></tr><%
										}
									} %></tbody></table></div><table class="navBar"><COL class="col1"><COL class="col2"><tr><TD></TD><td><button type="button" onclick="btnAddEnv_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnAgr")%>" title="<%=LabelManager.getToolTip(labelSet,"btnAgr")%>"><%=LabelManager.getNameWAccess(labelSet,"btnAgr")%></button><button type="button" onclick="btnDelEnv_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnEli")%>" title="<%=LabelManager.getToolTip(labelSet,"btnEli")%>"><%=LabelManager.getNameWAccess(labelSet,"btnEli")%></button></td></tr></table></div></div><div type="tab" style="visibility:hidden" style="visibility:hidden;" tabTitle="<%=LabelManager.getToolTip(labelSet,"tabSim")%>" tabText="<%=LabelManager.getName(labelSet,"tabSim")%>"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtSimData")%></DIV><table class="tblFormLayout"><COL class="col1"><COL class="col2"><COL class="col3"><COL class="col4"><tr><td><%=LabelManager.getNameWAccess(labelSet,"lblSimPoolType")%>:</td><td><select name="simType" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblSimPoolType")%>"><option></option><option value="<%= PoolVo.SIM_TYPE_HUMAN %>" <%= (poolVo != null && poolVo.getPoolSimType() != null && poolVo.getPoolSimType().intValue() == PoolVo.SIM_TYPE_HUMAN)?"selected":"" %>><%=LabelManager.getName(labelSet,"lblSimPoolTypeH")%></option><option value="<%= PoolVo.SIM_TYPE_AUTOMATIC %>" <%= (poolVo != null && poolVo.getPoolSimType() != null && poolVo.getPoolSimType().intValue() == PoolVo.SIM_TYPE_AUTOMATIC)?"selected":"" %>><%=LabelManager.getName(labelSet,"lblSimPoolTypeA")%></option></select></td><td><%=LabelManager.getNameWAccess(labelSet,"lblSimPoolCal")%>:</td><td><select name="simCal" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblSimPoolCal")%>"><option value=""></option><%	
								for (Iterator it = dBean.getCalendars().iterator(); it.hasNext(); ) { 
								    CalendarVo calVo = (CalendarVo) it.next(); %><option value="<%= calVo.getCalendarId() %>" <%= (poolVo != null && calVo.getCalendarId().equals(poolVo.getPoolSimCalId()))?"selected":"" %>><%= calVo.getCalendarName() %></option><%
								} %></select></td></tr><tr><td><%=LabelManager.getNameWAccess(labelSet,"lblSimPoolCostH")%>:</td><td><input type="text" name="simCostH" onchange="validateNumber(this)" value="<%=dBean.fmtHTML((poolVo != null)?poolVo.getPoolSimCostHour():null)%>" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblSimPoolCostH")%>"></td><td><%=LabelManager.getNameWAccess(labelSet,"lblSimPoolCostF")%>:</td><td><input type="text" name="simCostF" onchange="validateNumber(this)" value="<%=dBean.fmtHTML((poolVo != null)?poolVo.getPoolSimCostFixed():null)%>" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblSimPoolCostF")%>"></td></tr></table></div></div></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD><button type="button" onclick="btnConf_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnCon")%>" title="<%=LabelManager.getToolTip(labelSet,"btnCon")%>"><%=LabelManager.getNameWAccess(labelSet,"btnCon")%></button><button type="button" onclick="btnBack_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnVol")%>" title="<%=LabelManager.getToolTip(labelSet,"btnVol")%>"><%=LabelManager.getNameWAccess(labelSet,"btnVol")%></button><button type="button" onclick="btnExit_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><%@include file="../../../components/scripts/server/endInc.jsp" %><script language=javascript>
	var MSG_MUST_HAVE_ENV = "<%=LabelManager.getName(labelSet,"msgDebIngAmb")%>";
	
	function btnConf_click(){
	if (verifyRequiredObjects()) {
		if(isValidName(document.getElementById("txtName").value)){
			<%if(dBean.isModeGlobal()){%>
			if(document.getElementById("chkTodEnv").checked == true || (document.getElementById("chkTodEnv").checked != true && document.getElementById("gridEnv").rows.length != 0)){
			<%}%>
				document.getElementById("frmMain").action = "security.GroupsAction.do?action=confirm";
				submitForm(document.getElementById("frmMain"));
			<%if(dBean.isModeGlobal()){%>
			} else {
				alert(MSG_MUST_HAVE_ENV);
			}
			<%}%>
		}
	}
}
</script><script language="javascript" src='<%=Parameters.ROOT_PATH%>/programs/security/groups/update.js'></script>