<%@page import="com.dogma.vo.*"%><%@page import="java.util.*"%><%@page import="com.st.util.XMLUtils"%><%@include file="../../../components/scripts/server/startInc.jsp" %><HTML><head><%@include file="../../../components/scripts/server/headInclude.jsp" %></head><body onload="document.getElementById('divTree').style.height=((getStageHeight()-70)+'px')"><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.security.FunctionalityBean"></jsp:useBean><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,dBean.isModeGlobal()?"titFun":"titFunEnv")%></TD><TD></TD></TR></TABLE><div id="divContent"><form id="frmMain" name="frmMain" method="POST"><table id="treeTable" height="100%"><tr><td valign="top"><div id="divTree" style="width:500px;overflow:auto"><%out.println(XMLUtils.transform(dBean.getEnvId(request),dBean.getFunctionalitiesXML(request),"/programs/security/functionality/tblTree.xsl"));%></div></td><td align=left valign=top><table><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblNom")%>"><%=LabelManager.getNameWAccess(labelSet,"lblNom")%>:</td><td colspan=3><input name="txtNom" id="txtNom" p_required=true maxlength="255" size=40 accesskey="<%=LabelManager.getAccessKey(labelSet,"lblNom")%>"></td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblUrl")%>"><%=LabelManager.getNameWAccess(labelSet,"lblUrl")%>:</td><td colspan=3><input name="txtUrl" id="txtUrl" maxlength="250" size=40 accesskey="<%=LabelManager.getAccessKey(labelSet,"lblUrl")%>"></td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblTooTip")%>"><%=LabelManager.getNameWAccess(labelSet,"lblTooTip")%>:</td><td colspan=3><input name="txtToolTip" id="txtToolTip" maxlength="255" size=40 accesskey="<%=LabelManager.getAccessKey(labelSet,"lblTooTip")%>"></td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblTip")%>"><%=LabelManager.getNameWAccess(labelSet,"lblTip")%>:</td><td colspan=3><div style="display:none"><input type=text class="txtReadOnly" readonly id="txtTyp"></div><div><select name="cmbTyp" id="cmbTyp" p_required=true><option value="L"><%=LabelManager.getName(labelSet,"lblHoj")%></option><option value="F"><%=LabelManager.getName(labelSet,"lblCar")%></option></select></div></td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblPad")%>"><%=LabelManager.getNameWAccess(labelSet,"lblPad")%>:</td><td colspan=3><input type=text class="txtReadOnly" readonly id=txtFather style="display:none"><select name="cmbFather" id="cmbFather"><option/><%
											Collection col = dBean.getSortedFatherFunctionalities(request);
											if(col!=null){
												Iterator it = col.iterator();
												FunctionalityVo fVo = null;
												while(it.hasNext()){
													fVo = (FunctionalityVo)it.next();
													out.print("<option value=\"" + fVo.getFncId() + "\">" + fVo.getFncLabelName() + "</option>"); 
												}
											}
										%></select></td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblOrd")%>"><%=LabelManager.getNameWAccess(labelSet,"lblOrd")%>:</td><td colspan=3><input name="txtOrd" id="txtOrd" maxlength="4" p_required=true size=4 p_numeric="true" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblOrd")%>"></td></tr><tr><td title="<%=LabelManager.getToolTip(labelSet,"lblTipEje")%>"><%=LabelManager.getNameWAccess(labelSet,"lblTipEje")%>:</td><td colspan=3><div style="display:none"><input type=text class="txtReadOnly" readonly id="txtOpen"></div><div><select name="cmbOpen" id="cmbOpen" p_required=true><option value="T"><%=LabelManager.getName(labelSet,"lblMisVen")%></option><option value="F"><%=LabelManager.getName(labelSet,"lblNueVen")%></option></select></div></td></tr><tr><td colspan="4"><input type=hidden name="hidFncId" id="hidFncId"><input type=hidden name="hidFncGlobal" id="hidFncGlobal"><button type="button" id="btnNew" onclick="btnNew_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnCre")%>" title="<%=LabelManager.getToolTip(labelSet,"btnCre")%>"><%=LabelManager.getNameWAccess(labelSet,"btnCre")%></button><button type="button" id="btnUpd" onclick="btnUpd_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnAct")%>" title="<%=LabelManager.getToolTip(labelSet,"btnAct")%>"><%=LabelManager.getNameWAccess(labelSet,"btnAct")%></button><button type="button" id="btnDel" disabled onclick="btnDel_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnEli")%>" title="<%=LabelManager.getToolTip(labelSet,"btnEli")%>"><%=LabelManager.getNameWAccess(labelSet,"btnEli")%></button></td></tr></table></td></tr></table></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD align="right"><button type="button" onclick="btnConf_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnCon")%>" title="<%=LabelManager.getToolTip(labelSet,"btnCon")%>"><%=LabelManager.getNameWAccess(labelSet,"btnCon")%></button><button type="button" onclick="btnDep_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnDep")%>" title="<%=LabelManager.getToolTip(labelSet,"btnDep")%>"><%=LabelManager.getNameWAccess(labelSet,"btnDep")%></button><button type="button" onclick="btnExit_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><%@include file="../../../components/scripts/server/endInc.jsp" %><script language="javascript" defer=true src='<%=Parameters.ROOT_PATH%>/programs/security/functionality/main.js'></script><script language="javascript">
var ADM_FNC_FATHER = <%=Parameters.ADMIN_FNC_ID%>;
var ADM_GLOBAL = <%= dBean.isModeGlobal() %>;
var GNR_CHK_ONLY_ONE_FUNC = "<%= LabelManager.getName(labelSet,"msgDebSelSolUnaFunc") %>";
var GNR_CHK_AT_LEAST_ONE_FUNC = "<%= LabelManager.getName(labelSet,"msgDebSelUnaFun") %>";
<%if (dBean.getId() != null){%>
document.body.onload=function(){
	selectSelected(<%=dBean.getId()%>);
}
<%}%></script>