<%@page import="com.dogma.vo.*"%><%@page import="com.dogma.vo.filter.*"%><%@page import="java.util.*"%><%@include file="../../../components/scripts/server/startInc.jsp" %><HTML><head><%@include file="../../../components/scripts/server/headInclude.jsp" %></head><body><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.security.UserSubstituteBean"></jsp:useBean><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,"titSusHist")%></TD><TD></TD></TR></TABLE><DIV id="divContent" class="divContent"><form id="frmMain" name="frmMain" method="POST"><DIV class="subTit"><%=LabelManager.getName(labelSet,"sbtRes")%></DIV><div type="grid" id="gridList" style="height:<%=Parameters.SCREEN_LIST_SIZE%>px"><table width="500px" cellpadding="0" cellspacing="0"><thead><tr><th min_width="250px" style="width:250px" title="<%=LabelManager.getToolTip(labelSet,"lblLog")%>"><%=LabelManager.getName(labelSet,"lblLog")%></th><th min_width="120px" style="min-width:120px;width:50%" title="<%=LabelManager.getToolTip(labelSet,"lblDteFrom")%>"><%=LabelManager.getName(labelSet,"lblDteFrom")%></th><th min_width="120px" style="min-width:120px;width:50%" title="<%=LabelManager.getToolTip(labelSet,"lblDteTo")%>"><%=LabelManager.getName(labelSet,"lblDteTo")%></th></tr></thead><tbody><%	Collection col = dBean.getUserHistory();
							if (col != null) {
								Iterator it = col.iterator();
								int i = 0;
								UsersSubstitutesVo uVO = null;
								while (it.hasNext()) {
									uVO = (UsersSubstitutesVo) it.next(); %><tr><td><%=dBean.fmtHTML(uVO.getUsrLogin())%></td><td style="min-width:120px"><%=com.dogma.util.DogmaUtil.dateToString(dBean.getEnvId(request), uVO.getStartDate())%></td><td style="min-width:120px"><%=com.dogma.util.DogmaUtil.dateToString(dBean.getEnvId(request), uVO.getEndDate())%></td></tr><%i++;%><%	}
							}%></tbody></table></div><table class="navBar"><COL class="col1"><COL class="col2"><tr><td><button type="button" onclick="btnBack_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnVol")%>" title="<%=LabelManager.getToolTip(labelSet,"btnVol")%>"><%=LabelManager.getNameWAccess(labelSet,"btnVol")%></button></td></tr></table></form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><TR><TD></TD><TD><button type="button" onclick="splash()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></TD></TR></TABLE></body></html><%@include file="../../../components/scripts/server/endInc.jsp" %><script language="javascript"  src='<%=Parameters.ROOT_PATH%>/programs/security/usersSubstitutes/list.js'></script><script language="javascript">
function btnBack_click(){
		document.getElementById("frmMain").action = "security.UserSubstituteAction.do?action=backToList";
		submitForm(document.getElementById("frmMain"));
}
</script>