<%@page import="com.dogma.vo.*"%><%@page import="java.util.*"%><%@page import="com.dogma.vo.custom.TskDefinitionVo"%><%@include file="../../../components/scripts/server/startInc.jsp" %><HTML><head><%@include file="../../../components/scripts/server/headInclude.jsp" %></head><body><jsp:useBean id="dBean" scope="session" class="com.dogma.bean.administration.TaskBean"></jsp:useBean><%
String event = request.getParameter("event");
try {
%><!--     - USUARIOS A SER NOTIFICADOS          --><TABLE class="pageTop"><COL class="col1"><COL class="col2"><TR><TD><%=LabelManager.getName(labelSet,"titTskNot" + event)%></TD><TD></TD></TR></TABLE><DIV id="divContent" class="divContent"><form id="frmMain" name="frmMain" method="POST" target="frmSubmit" onSubmit="return false"><IFRAME id="frmSubmit" name="frmSubmit" style="display:none"></IFRAME><iframe name="iframeMessages" id="iframeMessages" src="<%=Parameters.ROOT_PATH%>/frames/feedBackWin.jsp" style="display:none"  class="feedBackFrame" frameborder="no"  ></iframe><!-- subject (solo si es email) --><%=LabelManager.getNameWAccess(labelSet,"lblSubMen")%>:<br><% TskNotMessageVo messageVo = dBean.getTskDefinitionVo().getTskNotMessage(event); %><input  size="70" maxlength="1000" name="txtSub" id="txtSub" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblSubMen") %>" value="<%= (messageVo != null)?messageVo.getTskNotSubject():"" %>"><br><br><!-- cuerpo de mensaje --><%=LabelManager.getNameWAccess(labelSet,"lblTexMen")%>:<br><textarea cols="90" rows="4" name="txtMes" id="txtMes" accesskey="<%=LabelManager.getAccessKey(labelSet,"lblTexMen") %>"><%= (messageVo != null)?messageVo.getTskNotMessage():"" %></textarea><br><br><%=LabelManager.getName(labelSet,"lblTskMenTok1") %><%=LabelManager.getName(labelSet,"lblTskMenTok3") %><%=LabelManager.getName(labelSet,"lblTskMenTok2") %><form></div><TABLE class="pageBottom"><COL class="col1"><COL class="col2"><tr><td><button type="button" onclick="btnDefMessage_click()" accessKey="<%=LabelManager.getAccessKey(labelSet,"btnDefMes")%>" title="<%=LabelManager.getToolTip(labelSet,"btnDefMes")%>"><%=LabelManager.getNameWAccess(labelSet,"btnDefMes")%></button></td><td><button type="button" onclick="btnConfMessage_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnCon")%>" title="<%=LabelManager.getToolTip(labelSet,"btnCon")%>"><%=LabelManager.getNameWAccess(labelSet,"btnCon")%></button><button type="button" onclick="btnExitMessage_click()" accesskey="<%=LabelManager.getAccessKey(labelSet,"btnSal")%>" title="<%=LabelManager.getToolTip(labelSet,"btnSal")%>"><%=LabelManager.getNameWAccess(labelSet,"btnSal")%></button></td></tr></table></html><SCRIPT>
  TYPE_NUMERIC = "<%= AttributeVo.TYPE_NUMERIC %>";
  TYPE_DATE = "<%= AttributeVo.TYPE_DATE %>";
  TYPE_STRING = "<%= AttributeVo.TYPE_STRING %>";
  EVENT = "<%= event %>";
  DEFAULT_MESSAGE = "<%= messageVo.getDefaultMessage(uData.getLabelSetId(),uData.getLangId()) %>";
</script><script src="<%=Parameters.ROOT_PATH%>/programs/administration/tasks/update.js"></script><%} catch (Exception e) { e.printStackTrace(); } %>